export const itemsid = {
    "伤害类型":"###################################",
    "anvil":"被铁砧砸",
    "blockExplosion":"方块爆炸",
    "campfire":"被营火烫",
    "charging":"貌似并没有这种死法",
    "contact":"接触",
    "drowning":"溺水了",
    "entityAttack":"实体攻击",
    "entityExplosion":"实体爆炸",
    "fall":"摔下来了",
    "fallingBlock":"下落的方块",
    "fire":"火灾",
    "fireTick":"身子着火",
    "fireworks":"放烟花被崩",
    "flyIntoWall":"飞到墙上坠机了",
    "freezing":"冻死了",
    "lava":"在岩浆里游泳",
    "lightning":"遭雷劈了",
    "maceSmash":"被风锤击碎了",
    "magic":"魔法攻击",
    "magma":"在岩浆块上暖脚",
    "none":"没有伤害",
    "override":"覆写伤害",
    "piston":"活塞",
    "projectile":"弹射物攻击",
    "ramAttack":"被山羊撞了",
    "selfDestruct":"/kill命令",
    "sonicBoom":"被远古守卫吼死了",
    "soulCampfire":"被灵魂营火烫",
    "stalactite":"被钟乳石砸",
    "stalagmite":"被石笋砸",
    "starve":"饿死了",
    "suffocation":"窒息了",
    "suicide":"自杀了",
    "temperature":"水土不服",
    "thorns":"反甲",
    "void":"掉入虚空",
    "wither":"凋谢了",
    "维度":"#####################################",
    "minecraft:overworld":"主世界",
    "minecraft:nether":"地狱",
    "minecraft:the_end":"末地",
    "方块":"#####################################",
    "minecraft:acacia_button":"金合欢木按钮",
    "minecraft:acacia_door":"金合欢木门",
    "minecraft:acacia_double_slab":"金合欢木双重台阶",
    "minecraft:acacia_fence":"金合欢木栅栏",
    "minecraft:acacia_fence_gate":"金合欢木栅栏门",
    "minecraft:acacia_hanging_sign":"金合欢木悬挂告示牌",
    "minecraft:acacia_leaves":"金合欢木树叶",
    "minecraft:acacia_log":"金合欢木原木",
    "minecraft:acacia_planks":"金合欢木木板",
    "minecraft:acacia_pressure_plate":"金合欢木压力板",
    "minecraft:acacia_sapling":"金合欢木树苗",
    "minecraft:acacia_slab":"金合欢木台阶",
    "minecraft:acacia_stairs":"金合欢木楼梯",
    "minecraft:acacia_standing_sign":"金合欢木立式告示牌",
    "minecraft:acacia_trapdoor":"金合欢木活板门",
    "minecraft:acacia_wall_sign":"金合欢木墙挂告示牌",
    "minecraft:acacia_wood":"金合欢木",
    "minecraft:activator_rail":"激活铁轨",
    "minecraft:air":"空气",
    "minecraft:allow":"允许方块",
    "minecraft:amethyst_block":"紫水晶块",
    "minecraft:amethyst_cluster":"紫晶簇",
    "minecraft:ancient_debris":"远古残骸",
    "minecraft:andesite":"安山岩",
    "minecraft:andesite_double_slab":"安山岩双重台阶",
    "minecraft:andesite_slab":"安山岩台阶",
    "minecraft:andesite_stairs":"安山岩楼梯",
    "minecraft:andesite_wall":"安山岩墙",
    "minecraft:anvil":"铁砧",
    "minecraft:azalea":"杜鹃花",
    "minecraft:azalea_leaves":"杜鹃花叶子",
    "minecraft:azalea_leaves_flowered":"开花的杜鹃花叶子",
    "minecraft:bamboo":"竹子",
    "minecraft:bamboo_block":"竹块",
    "minecraft:bamboo_button":"竹按钮",
    "minecraft:bamboo_door":"竹门",
    "minecraft:bamboo_double_slab":"竹双重台阶",
    "minecraft:bamboo_fence":"竹栅栏",
    "minecraft:bamboo_fence_gate":"竹栅栏门",
    "minecraft:bamboo_hanging_sign":"竹悬挂告示牌",
    "minecraft:bamboo_mosaic":"竹马赛克",
    "minecraft:bamboo_mosaic_double_slab":"竹马赛克双重台阶",
    "minecraft:bamboo_mosaic_slab":"竹马赛克台阶",
    "minecraft:bamboo_mosaic_stairs":"竹马赛克楼梯",
    "minecraft:bamboo_planks":"竹木板",
    "minecraft:bamboo_pressure_plate":"竹压力板",
    "minecraft:bamboo_sapling":"竹笋",
    "minecraft:bamboo_slab":"竹台阶",
    "minecraft:bamboo_stairs":"竹楼梯",
    "minecraft:bamboo_standing_sign":"竹立式告示牌",
    "minecraft:bamboo_trapdoor":"竹活板门",
    "minecraft:bamboo_wall_sign":"竹墙挂告示牌",
    "minecraft:barrel":"木桶",
    "minecraft:barrier":"屏障",
    "minecraft:basalt":"玄武岩",
    "minecraft:beacon":"信标",
    "minecraft:bed":"床",
    "minecraft:bedrock":"基岩",
    "minecraft:bee_nest":"蜂巢",
    "minecraft:beehive":"蜂箱",
    "minecraft:beetroot":"甜菜根",
    "minecraft:bell":"钟",
    "minecraft:big_dripleaf":"大垂滴叶",
    "minecraft:birch_button":"白桦木按钮",
    "minecraft:birch_door":"白桦木门",
    "minecraft:birch_double_slab":"白桦木双重台阶",
    "minecraft:birch_fence":"白桦木栅栏",
    "minecraft:birch_fence_gate":"白桦木栅栏门",
    "minecraft:birch_hanging_sign":"白桦木悬挂告示牌",
    "minecraft:birch_leaves":"白桦木树叶",
    "minecraft:birch_log":"白桦木原木",
    "minecraft:birch_planks":"白桦木木板",
    "minecraft:birch_pressure_plate":"白桦木压力板",
    "minecraft:birch_sapling":"白桦木树苗",
    "minecraft:birch_slab":"白桦木台阶",
    "minecraft:birch_stairs":"白桦木楼梯",
    "minecraft:birch_standing_sign":"白桦木立式告示牌",
    "minecraft:birch_trapdoor":"白桦木活板门",
    "minecraft:birch_wall_sign":"白桦木墙挂告示牌",
    "minecraft:birch_wood":"白桦木",
    "minecraft:black_candle":"黑色蜡烛",
    "minecraft:black_candle_cake":"黑色蜡烛蛋糕",
    "minecraft:black_carpet":"黑色地毯",
    "minecraft:black_concrete":"黑色混凝土",
    "minecraft:black_concrete_powder":"黑色混凝土粉末",
    "minecraft:black_glazed_terracotta":"黑色带釉陶瓦",
    "minecraft:black_shulker_box":"黑色潜影盒",
    "minecraft:black_stained_glass":"黑色染色玻璃",
    "minecraft:black_stained_glass_pane":"黑色染色玻璃板",
    "minecraft:black_terracotta":"黑色陶瓦",
    "minecraft:black_wool":"黑色羊毛",
    "minecraft:blackstone":"黑石",
    "minecraft:blackstone_double_slab":"黑石双重台阶",
    "minecraft:blackstone_slab":"黑石台阶",
    "minecraft:blackstone_stairs":"黑石楼梯",
    "minecraft:blackstone_wall":"黑石墙",
    "minecraft:blast_furnace":"高炉",
    "minecraft:blue_candle":"蓝色蜡烛",
    "minecraft:blue_candle_cake":"蓝色蜡烛蛋糕",
    "minecraft:blue_carpet":"蓝色地毯",
    "minecraft:blue_concrete":"蓝色混凝土",
    "minecraft:blue_concrete_powder":"蓝色混凝土粉末",
    "minecraft:blue_glazed_terracotta":"蓝色带釉陶瓦",
    "minecraft:blue_ice":"蓝冰",
    "minecraft:blue_shulker_box":"蓝色潜影盒",
    "minecraft:blue_stained_glass":"蓝色染色玻璃",
    "minecraft:blue_stained_glass_pane":"蓝色染色玻璃板",
    "minecraft:blue_terracotta":"蓝色陶瓦",
    "minecraft:blue_wool":"蓝色羊毛",
    "minecraft:bone_block":"骨块",
    "minecraft:bookshelf":"书架",
    "minecraft:border_block":"边界方块",
    "minecraft:brain_coral":"脑纹珊瑚",
    "minecraft:brain_coral_block":"脑纹珊瑚块",
    "minecraft:brain_coral_fan":"脑纹珊瑚扇",
    "minecraft:brain_coral_wall_fan":"墙上的脑纹珊瑚扇",
    "minecraft:brewing_stand":"酿造台",
    "minecraft:brick_block":"砖块",
    "minecraft:brick_double_slab":"砖双重台阶",
    "minecraft:brick_slab":"砖台阶",
    "minecraft:brick_stairs":"砖楼梯",
    "minecraft:brick_wall":"砖墙",
    "minecraft:brown_candle":"棕色蜡烛",
    "minecraft:brown_candle_cake":"棕色蜡烛蛋糕",
    "minecraft:brown_carpet":"棕色地毯",
    "minecraft:brown_concrete":"棕色混凝土",
    "minecraft:brown_concrete_powder":"棕色混凝土粉末",
    "minecraft:brown_glazed_terracotta":"棕色带釉陶瓦",
    "minecraft:brown_mushroom":"棕色蘑菇",
    "minecraft:brown_mushroom_block":"棕色蘑菇块",
    "minecraft:brown_shulker_box":"棕色潜影盒",
    "minecraft:brown_stained_glass":"棕色染色玻璃",
    "minecraft:brown_stained_glass_pane":"棕色染色玻璃板",
    "minecraft:brown_terracotta":"棕色陶瓦",
    "minecraft:brown_wool":"棕色羊毛",
    "minecraft:bubble_column":"气泡柱",
    "minecraft:bubble_coral":"泡泡珊瑚",
    "minecraft:bubble_coral_block":"泡泡珊瑚块",
    "minecraft:bubble_coral_fan":"泡泡珊瑚扇",
    "minecraft:bubble_coral_wall_fan":"墙上的泡泡珊瑚扇",
    "minecraft:budding_amethyst":"紫水晶母岩",
    "minecraft:cactus":"仙人掌",
    "minecraft:cake":"蛋糕",
    "minecraft:calcite":"方解石",
    "minecraft:calibrated_sculk_sensor":"校准的潜声传感器",
    "minecraft:camera":"相机",
    "minecraft:campfire":"篝火",
    "minecraft:candle":"蜡烛",
    "minecraft:candle_cake":"蜡烛蛋糕",
    "minecraft:carrots":"胡萝卜",
    "minecraft:cartography_table":"制图台",
    "minecraft:carved_pumpkin":"雕刻南瓜",
    "minecraft:cauldron":"炼药锅",
    "minecraft:cave_vines":"洞穴藤蔓",
    "minecraft:cave_vines_body_with_berries":"带果的洞穴藤蔓",
    "minecraft:cave_vines_head_with_berries":"带果的洞穴藤蔓头",
    "minecraft:chain":"锁链",
    "minecraft:chain_command_block":"连锁命令方块",
    "minecraft:chemical_heat":"化学热",
    "minecraft:cherry_button":"樱花木按钮",
    "minecraft:cherry_door":"樱花木门",
    "minecraft:cherry_double_slab":"樱花木双重台阶",
    "minecraft:cherry_fence":"樱花木栅栏",
    "minecraft:cherry_fence_gate":"樱花木栅栏门",
    "minecraft:cherry_hanging_sign":"樱花木悬挂告示牌",
    "minecraft:cherry_leaves":"樱花树叶",
    "minecraft:cherry_log":"樱花原木",
    "minecraft:cherry_planks":"樱花木板",
    "minecraft:cherry_pressure_plate":"樱花木压力板",
    "minecraft:cherry_sapling":"樱花树苗",
    "minecraft:cherry_slab":"樱花木台阶",
    "minecraft:cherry_stairs":"樱花木楼梯",
    "minecraft:cherry_standing_sign":"樱花木立式告示牌",
    "minecraft:cherry_trapdoor":"樱花木活板门",
    "minecraft:cherry_wall_sign":"樱花木墙挂告示牌",
    "minecraft:cherry_wood":"樱花木",
    "minecraft:chest":"箱子",
    "minecraft:chipped_anvil":"磨损的铁砧",
    "minecraft:chiseled_bookshelf":"錾制书架",
    "minecraft:chiseled_copper":"錾制铜块",
    "minecraft:chiseled_deepslate":"錾制深层石材",
    "minecraft:chiseled_nether_bricks":"錾制下界砖块",
    "minecraft:chiseled_polished_blackstone":"錾制磨制黑石",
    "minecraft:chiseled_quartz_block":"錾制石英块",
    "minecraft:chiseled_red_sandstone":"錾制红沙石",
    "minecraft:chiseled_sandstone":"錾制沙石",
    "minecraft:chiseled_stone_bricks":"錾制石砖",
    "minecraft:chiseled_tuff":"錾制凝灰岩",
    "minecraft:chiseled_tuff_bricks":"錾制凝灰岩砖",
    "minecraft:chorus_flower":"紫颂花",
    "minecraft:chorus_plant":"紫颂树",
    "minecraft:clay":"粘土",
    "minecraft:client_request_placeholder_block":"客户端请求占位块",
    "minecraft:coal_block":"煤炭块",
    "minecraft:coal_ore":"煤炭矿石",
    "minecraft:coarse_dirt":"砂土",
    "minecraft:cobbled_deepslate":"圆石深层石材",
    "minecraft:cobbled_deepslate_double_slab":"圆石深层石材双重台阶",
    "minecraft:cobbled_deepslate_slab":"圆石深层石材台阶",
    "minecraft:cobbled_deepslate_stairs":"圆石深层石材楼梯",
    "minecraft:cobbled_deepslate_wall":"圆石深层石材墙",
    "minecraft:cobblestone":"圆石",
    "minecraft:cobblestone_double_slab":"圆石双重台阶",
    "minecraft:cobblestone_slab":"圆石台阶",
    "minecraft:cobblestone_wall":"圆石墙",
    "minecraft:cocoa":"可可豆",
    "minecraft:colored_torch_blue":"蓝色彩色火把",
    "minecraft:colored_torch_green":"绿色彩色火把",
    "minecraft:colored_torch_purple":"紫色彩色火把",
    "minecraft:colored_torch_red":"红色彩色火把",
    "minecraft:command_block":"命令方块",
    "minecraft:composter":"堆肥桶",
    "minecraft:compound_creator":"化合物创建器",
    "minecraft:conduit":"潮涌核心",
    "minecraft:copper_block":"铜块",
    "minecraft:copper_bulb":"铜质灯泡",
    "minecraft:copper_door":"铜门",
    "minecraft:copper_grate":"铜质格栅",
    "minecraft:copper_ore":"铜矿石",
    "minecraft:copper_trapdoor":"铜活板门",
    "minecraft:coral_fan_dead":"死亡的珊瑚扇",
    "minecraft:cracked_deepslate_bricks":"裂开的深层石砖",
    "minecraft:cracked_deepslate_tiles":"裂开的深层石瓦",
    "minecraft:cracked_nether_bricks":"裂开的下界砖",
    "minecraft:cracked_polished_blackstone_bricks":"裂开的磨制黑石砖",
    "minecraft:cracked_stone_bricks":"裂开的石砖",
    "minecraft:crafter":"合成器",
    "minecraft:crafting_table":"工作台",
    "minecraft:crimson_button":"绯红按钮",
    "minecraft:crimson_door":"绯红门",
    "minecraft:crimson_double_slab":"绯红双重台阶",
    "minecraft:crimson_fence":"绯红栅栏",
    "minecraft:crimson_fence_gate":"绯红栅栏门",
    "minecraft:crimson_fungus":"绯红菌",
    "minecraft:crimson_hanging_sign":"绯红悬挂告示牌",
    "minecraft:crimson_hyphae":"绯红菌柄",
    "minecraft:crimson_nylium":"绯红下界菌岩",
    "minecraft:crimson_planks":"绯红木木板",
    "minecraft:crimson_pressure_plate":"绯红木压力板",
    "minecraft:crimson_roots":"绯红根",
    "minecraft:crimson_slab":"绯红木台阶",
    "minecraft:crimson_stairs":"绯红木楼梯",
    "minecraft:crimson_standing_sign":"绯红木立式告示牌",
    "minecraft:crimson_stem":"绯红茎",
    "minecraft:crimson_trapdoor":"绯红木活板门",
    "minecraft:crimson_wall_sign":"绯红木墙挂告示牌",
    "minecraft:crying_obsidian":"哭泣的黑曜石",
    "minecraft:cut_copper":"切割铜块",
    "minecraft:cut_copper_slab":"切割铜台阶",
    "minecraft:cut_copper_stairs":"切割铜楼梯",
    "minecraft:cut_red_sandstone":"切割红沙石",
    "minecraft:cut_red_sandstone_double_slab":"切割红沙石双重台阶",
    "minecraft:cut_red_sandstone_slab":"切割红沙石台阶",
    "minecraft:cut_sandstone":"切割沙石",
    "minecraft:cut_sandstone_double_slab":"切割沙石双重台阶",
    "minecraft:cut_sandstone_slab":"切割沙石台阶",
    "minecraft:cyan_candle":"青色蜡烛",
    "minecraft:cyan_candle_cake":"青色蜡烛蛋糕",
    "minecraft:cyan_carpet":"青色地毯",
    "minecraft:cyan_concrete":"青色混凝土",
    "minecraft:cyan_concrete_powder":"青色混凝土粉末",
    "minecraft:cyan_glazed_terracotta":"青色带釉陶瓦",
    "minecraft:cyan_shulker_box":"青色潜影盒",
    "minecraft:cyan_stained_glass":"青色染色玻璃",
    "minecraft:cyan_stained_glass_pane":"青色染色玻璃板",
    "minecraft:cyan_terracotta":"青色陶瓦",
    "minecraft:cyan_wool":"青色羊毛",
    "minecraft:damaged_anvil":"损坏的铁砧",
    "minecraft:dandelion":"蒲公英",
    "minecraft:dark_oak_button":"深色橡木按钮",
    "minecraft:dark_oak_door":"深色橡木门",
    "minecraft:dark_oak_double_slab":"深色橡木双重台阶",
    "minecraft:dark_oak_fence":"深色橡木栅栏",
    "minecraft:dark_oak_fence_gate":"深色橡木栅栏门",
    "minecraft:dark_oak_hanging_sign":"深色橡木悬挂告示牌",
    "minecraft:dark_oak_leaves":"深色橡木树叶",
    "minecraft:dark_oak_log":"深色橡木原木",
    "minecraft:dark_oak_planks":"深色橡木木板",
    "minecraft:dark_oak_pressure_plate":"深色橡木压力板",
    "minecraft:dark_oak_sapling":"深色橡木树苗",
    "minecraft:dark_oak_slab":"深色橡木台阶",
    "minecraft:dark_oak_stairs":"深色橡木楼梯",
    "minecraft:dark_oak_trapdoor":"深色橡木活板门",
    "minecraft:dark_oak_wood":"深色橡木",
    "minecraft:dark_prismarine":"暗海晶石",
    "minecraft:dark_prismarine_double_slab":"暗海晶石双重台阶",
    "minecraft:dark_prismarine_slab":"暗海晶石台阶",
    "minecraft:dark_prismarine_stairs":"暗海晶石楼梯",
    "minecraft:darkoak_standing_sign":"深色橡木立式告示牌",
    "minecraft:darkoak_wall_sign":"深色橡木墙挂告示牌",
    "minecraft:daylight_detector":"阳光探测器",
    "minecraft:daylight_detector_inverted":"反向阳光探测器",
    "minecraft:dead_brain_coral":"死亡的脑珊瑚",
    "minecraft:dead_brain_coral_wall_fan":"墙上的死亡的脑珊瑚扇",
    "minecraft:dead_bubble_coral":"死亡的泡泡珊瑚",
    "minecraft:dead_bubble_coral_wall_fan":"墙上的死亡的泡泡珊瑚扇",
    "minecraft:dead_fire_coral":"死亡的火焰珊瑚",
    "minecraft:dead_fire_coral_wall_fan":"墙上的死亡的火焰珊瑚扇",
    "minecraft:dead_horn_coral":"死亡的角珊瑚",
    "minecraft:dead_horn_coral_wall_fan":"墙上的死亡的角珊瑚扇",
    "minecraft:dead_tube_coral":"死亡的管珊瑚",
    "minecraft:dead_tube_coral_wall_fan":"墙上的死亡的管珊瑚扇",
    "minecraft:dead_brain_coral_block":"死亡的脑珊瑚块",
    "minecraft:dead_bubble_coral":"死亡的泡泡珊瑚",
    "minecraft:dead_bubble_coral_block":"死亡的泡泡珊瑚块",
    "minecraft:dead_fire_coral":"死亡的火焰珊瑚",
    "minecraft:dead_fire_coral_block":"死亡的火焰珊瑚块",
    "minecraft:dead_horn_coral":"死亡的角珊瑚",
    "minecraft:dead_horn_coral_block":"死亡的角珊瑚块",
    "minecraft:dead_tube_coral":"死亡的管珊瑚",
    "minecraft:dead_tube_coral_block":"死亡的管珊瑚块",
    "minecraft:deadbush":"枯死的灌木",
    "minecraft:decorated_pot":"饰纹陶罐",
    "minecraft:deepslate":"深层石材",
    "minecraft:deepslate_brick_double_slab":"深层石砖双重台阶",
    "minecraft:deepslate_brick_slab":"深层石砖台阶",
    "minecraft:deepslate_brick_stairs":"深层石砖楼梯",
    "minecraft:deepslate_brick_wall":"深层石砖墙",
    "minecraft:deepslate_bricks":"深层石砖",
    "minecraft:deepslate_coal_ore":"深层石材煤矿石",
    "minecraft:deepslate_copper_ore":"深层石材铜矿石",
    "minecraft:deepslate_diamond_ore":"深层石材钻石矿石",
    "minecraft:deepslate_emerald_ore":"深层石材绿宝石矿石",
    "minecraft:deepslate_gold_ore":"深层石材金矿石",
    "minecraft:deepslate_iron_ore":"深层石材铁矿石",
    "minecraft:deepslate_lapis_ore":"深层石材青金石矿石",
    "minecraft:deepslate_redstone_ore":"深层石材红石矿石",
    "minecraft:deepslate_tile_double_slab":"深层石材瓦双重台阶",
    "minecraft:deepslate_tile_slab":"深层石材瓦台阶",
    "minecraft:deepslate_tile_stairs":"深层石材瓦楼梯",
    "minecraft:deepslate_tile_wall":"深层石材瓦墙",
    "minecraft:deepslate_tiles":"深层石材瓦",
    "minecraft:deny":"拒绝方块",
    "minecraft:deprecated_anvil":"已弃用的铁砧",
    "minecraft:deprecated_purpur_block_1":"已弃用的紫珀块1",
    "minecraft:deprecated_purpur_block_2":"已弃用的紫珀块2",
    "minecraft:detector_rail":"探测铁轨",
    "minecraft:diamond_block":"钻石块",
    "minecraft:diamond_ore":"钻石矿石",
    "minecraft:diorite":"闪长岩",
    "minecraft:diorite_double_slab":"闪长岩双重台阶",
    "minecraft:diorite_slab":"闪长岩台阶",
    "minecraft:diorite_stairs":"闪长岩楼梯",
    "minecraft:diorite_wall":"闪长岩墙",
    "minecraft:dirt":"泥土",
    "minecraft:dirt_with_roots":"带根泥土",
    "minecraft:dispenser":"发射器",
    "minecraft:double_cut_copper_slab":"双重切割铜台阶",
    "minecraft:double_plant":"双层植物",
    "minecraft:double_block_slab":"双重方块台阶",
    "minecraft:double_block_slab2":"双重方块台阶2",
    "minecraft:double_block_slab3":"双重方块台阶3",
    "minecraft:double_block_slab4":"双重方块台阶4",
    "minecraft:dragon_egg":"龙蛋",
    "minecraft:dried_kelp_block":"干海带块",
    "minecraft:dripstone_block":"滴水石块",
    "minecraft:dropper":"投掷器",
    "minecraft:element_0":"元素0",
    "minecraft:element_1":"元素1",
    "minecraft:element_10":"元素10",
    "minecraft:element_100":"元素100",
    "minecraft:element_101":"元素101",
    "minecraft:element_102":"元素102",
    "minecraft:element_103":"元素103",
    "minecraft:element_104":"元素104",
    "minecraft:element_105":"元素105",
    "minecraft:element_106":"元素106",
    "minecraft:element_107":"元素107",
    "minecraft:element_108":"元素108",
    "minecraft:element_109":"元素109",
    "minecraft:element_11":"元素11",
    "minecraft:element_110":"元素110",
    "minecraft:element_111":"元素111",
    "minecraft:element_112":"元素112",
    "minecraft:element_113":"元素113",
    "minecraft:element_114":"元素114",
    "minecraft:element_115":"元素115",
    "minecraft:element_116":"元素116",
    "minecraft:element_117":"元素117",
    "minecraft:element_118":"元素118",
    "minecraft:element_12":"元素12",
    "minecraft:element_13":"元素13",
    "minecraft:element_14":"元素14",
    "minecraft:element_15":"元素15",
    "minecraft:element_16":"元素16",
    "minecraft:element_17":"元素17",
    "minecraft:element_18":"元素18",
    "minecraft:element_19":"元素19",
    "minecraft:element_2":"元素2",
    "minecraft:element_20":"元素20",
    "minecraft:element_21":"元素21",
    "minecraft:element_22":"元素22",
    "minecraft:element_23":"元素23",
    "minecraft:element_24":"元素24",
    "minecraft:element_25":"元素25",
    "minecraft:element_26":"元素26",
    "minecraft:element_27":"元素27",
    "minecraft:element_28":"元素28",
    "minecraft:element_29":"元素29",
    "minecraft:element_3":"元素3",
    "minecraft:element_30":"元素30",
    "minecraft:element_31":"元素31",
    "minecraft:element_32":"元素32",
    "minecraft:element_33":"元素33",
    "minecraft:element_34":"元素34",
    "minecraft:element_35":"元素35",
    "minecraft:element_36":"元素36",
    "minecraft:element_37":"元素37",
    "minecraft:element_38":"元素38",
    "minecraft:element_39":"元素39",
    "minecraft:element_4":"元素4",
    "minecraft:element_40":"元素40",
    "minecraft:element_41":"元素41",
    "minecraft:element_42":"元素42",
    "minecraft:element_43":"元素43",
    "minecraft:element_44":"元素44",
    "minecraft:element_45":"元素45",
    "minecraft:element_46":"元素46",
    "minecraft:element_47":"元素47",
    "minecraft:element_48":"元素48",
    "minecraft:element_49":"元素49",
    "minecraft:element_5":"元素5",
    "minecraft:element_50":"元素50",
    "minecraft:element_51":"元素51",
    "minecraft:element_52":"元素52",
    "minecraft:element_53":"元素53",
    "minecraft:element_54":"元素54",
    "minecraft:element_55":"元素55",
    "minecraft:element_56":"元素56",
    "minecraft:element_57":"元素57",
    "minecraft:element_58":"元素58",
    "minecraft:element_59":"元素59",
    "minecraft:element_6":"元素6",
    "minecraft:element_60":"元素60",
    "minecraft:element_61":"元素61",
    "minecraft:element_62":"元素62",
    "minecraft:element_63":"元素63",
    "minecraft:element_64":"元素64",
    "minecraft:element_65":"元素65",
    "minecraft:element_66":"元素66",
    "minecraft:element_67":"元素67",
    "minecraft:element_68":"元素68",
    "minecraft:element_69":"元素69",
    "minecraft:element_7":"元素7",
    "minecraft:element_70":"元素70",
    "minecraft:element_71":"元素71",
    "minecraft:element_72":"元素72",
    "minecraft:element_73":"元素73",
    "minecraft:element_74":"元素74",
    "minecraft:element_75":"元素75",
    "minecraft:element_76":"元素76",
    "minecraft:element_77":"元素77",
    "minecraft:element_78":"元素78",
    "minecraft:element_79":"元素79",
    "minecraft:element_8":"元素8",
    "minecraft:element_80":"元素80",
    "minecraft:element_81":"元素81",
    "minecraft:element_82":"元素82",
    "minecraft:element_83":"元素83",
    "minecraft:element_84":"元素84",
    "minecraft:element_85":"元素85",
    "minecraft:element_86":"元素86",
    "minecraft:element_87":"元素87",
    "minecraft:element_88":"元素88",
    "minecraft:element_89":"元素89",
    "minecraft:element_9":"元素9",
    "minecraft:element_90":"元素90",
    "minecraft:element_91":"元素91",
    "minecraft:element_92":"元素92",
    "minecraft:element_93":"元素93",
    "minecraft:element_94":"元素94",
    "minecraft:element_95":"元素95",
    "minecraft:element_96":"元素96",
    "minecraft:element_97":"元素97",
    "minecraft:element_98":"元素98",
    "minecraft:element_99":"元素99",
    "minecraft:element_constructor":"元素构造器",
    "minecraft:emerald_block":"绿宝石块",
    "minecraft:emerald_ore":"绿宝石矿石",
    "minecraft:enchanting_table":"附魔台",
    "minecraft:end_brick_stairs":"末影砖楼梯",
    "minecraft:end_bricks":"末影砖",
    "minecraft:end_gateway":"末地折跃门",
    "minecraft:end_portal":"末地传送门",
    "minecraft:end_portal_frame":"末地传送门框架",
    "minecraft:end_rod":"末地烛",
    "minecraft:end_stone":"末地石",
    "minecraft:end_stone_brick_double_slab":"末地石砖双重台阶",
    "minecraft:end_stone_brick_slab":"末地石砖台阶",
    "minecraft:end_stone_brick_wall":"末地石砖墙",
    "minecraft:ender_chest":"末影箱",
    "minecraft:exposed_chiseled_copper":"暴露的錾制铜块",
    "minecraft:exposed_copper":"暴露的铜块",
    "minecraft:exposed_copper_bulb":"暴露的铜质灯泡",
    "minecraft:exposed_copper_door":"暴露的铜门",
    "minecraft:exposed_copper_grate":"暴露的铜质格栅",
    "minecraft:exposed_copper_trapdoor":"暴露的铜活板门",
    "minecraft:exposed_cut_copper":"暴露的切割铜块",
    "minecraft:exposed_cut_copper_slab":"暴露的切割铜台阶",
    "minecraft:exposed_cut_copper_stairs":"暴露的切割铜楼梯",
    "minecraft:exposed_double_cut_copper_slab":"暴露的双重切割铜台阶",
    "minecraft:farmland":"耕地",
    "minecraft:fence_gate":"栅栏门",
    "minecraft:fern":"蕨类植物",
    "minecraft:fire":"火",
    "minecraft:fire_coral":"火焰珊瑚",
    "minecraft:fire_coral_block":"火焰珊瑚块",
    "minecraft:fire_coral_fan":"火焰珊瑚扇",
    "minecraft:fire_coral_wall_fan":"墙上的火焰珊瑚扇",
    "minecraft:fletching_table":"制箭台",
    "minecraft:flower_pot":"花盆",
    "minecraft:flowering_azalea":"开花的杜鹃花",
    "minecraft:flowing_lava":"流动的熔岩",
    "minecraft:flowing_water":"流动的水",
    "minecraft:frame":"画框",
    "minecraft:frog_spawn":"青蛙刷怪蛋",
    "minecraft:frosted_ice":"霜冰",
    "minecraft:furnace":"熔炉",
    "minecraft:gilded_blackstone":"镶金黑石",
    "minecraft:glass":"玻璃",
    "minecraft:glass_pane":"玻璃板",
    "minecraft:glow_frame":"发光的画框",
    "minecraft:glow_lichen":"荧光地衣",
    "minecraft:glowingobsidian":"发光的黑曜石",
    "minecraft:glowstone":"荧石",
    "minecraft:gold_block":"金块",
    "minecraft:gold_ore":"金矿石",
    "minecraft:golden_rail":"动力铁轨",
    "minecraft:granite":"花岗岩",
    "minecraft:granite_double_slab":"花岗岩双重台阶",
    "minecraft:granite_slab":"花岗岩台阶",
    "minecraft:granite_stairs":"花岗岩楼梯",
    "minecraft:granite_wall":"花岗岩墙",
    "minecraft:grass_block":"草方块",
    "minecraft:grass_path":"草径",
    "minecraft:gravel":"沙砾",
    "minecraft:gray_candle":"灰色蜡烛",
    "minecraft:gray_candle_cake":"灰色蜡烛蛋糕",
    "minecraft:gray_carpet":"灰色地毯",
    "minecraft:gray_concrete":"灰色混凝土",
    "minecraft:gray_concrete_powder":"灰色混凝土粉末",
    "minecraft:gray_glazed_terracotta":"灰色带釉陶瓦",
    "minecraft:gray_shulker_box":"灰色潜影盒",
    "minecraft:gray_stained_glass":"灰色染色玻璃",
    "minecraft:gray_stained_glass_pane":"灰色染色玻璃板",
    "minecraft:gray_terracotta":"灰色陶瓦",
    "minecraft:gray_wool":"灰色羊毛",
    "minecraft:green_candle":"绿色蜡烛",
    "minecraft:green_candle_cake":"绿色蜡烛蛋糕",
    "minecraft:green_carpet":"绿色地毯",
    "minecraft:green_concrete":"绿色混凝土",
    "minecraft:green_concrete_powder":"绿色混凝土粉末",
    "minecraft:green_glazed_terracotta":"绿色带釉陶瓦",
    "minecraft:green_shulker_box":"绿色潜影盒",
    "minecraft:green_stained_glass":"绿色染色玻璃",
    "minecraft:green_stained_glass_pane":"绿色染色玻璃板",
    "minecraft:green_terracotta":"绿色陶瓦",
    "minecraft:green_wool":"绿色羊毛",
    "minecraft:grindstone":"磨石",
    "minecraft:hanging_roots":"垂根",
    "minecraft:hard_black_stained_glass":"硬黑色染色玻璃",
    "minecraft:hard_black_stained_glass_pane":"硬黑色染色玻璃板",
    "minecraft:hard_blue_stained_glass":"硬蓝色染色玻璃",
    "minecraft:hard_blue_stained_glass_pane":"硬蓝色染色玻璃板",
    "minecraft:hard_brown_stained_glass":"硬棕色染色玻璃",
    "minecraft:hard_brown_stained_glass_pane":"硬棕色染色玻璃板",
    "minecraft:hard_glass":"硬玻璃",
    "minecraft:hard_glass_pane":"硬玻璃板",
    "minecraft:hard_gray_stained_glass":"硬灰色染色玻璃",
    "minecraft:hard_gray_stained_glass_pane":"硬灰色染色玻璃板",
    "minecraft:hard_green_stained_glass":"硬绿色染色玻璃",
    "minecraft:hard_green_stained_glass_pane":"硬绿色染色玻璃板",
    "minecraft:hard_light_blue_stained_glass":"硬淡蓝色染色玻璃",
    "minecraft:hard_light_blue_stained_glass_pane":"硬淡蓝色染色玻璃板",
    "minecraft:hard_stained_glass":"硬染色玻璃",
    "minecraft:hard_light_gray_stained_glass":"硬浅灰色染色玻璃",
    "minecraft:hard_light_gray_stained_glass_pane":"硬浅灰色染色玻璃板",
    "minecraft:hard_lime_stained_glass":"硬黄绿色染色玻璃",
    "minecraft:hard_lime_stained_glass_pane":"硬黄绿色染色玻璃板",
    "minecraft:hard_magenta_stained_glass":"硬品红色染色玻璃",
    "minecraft:hard_magenta_stained_glass_pane":"硬品红色染色玻璃板",
    "minecraft:hard_orange_stained_glass":"硬橙色染色玻璃",
    "minecraft:hard_orange_stained_glass_pane":"硬橙色染色玻璃板",
    "minecraft:hard_pink_stained_glass":"硬粉红色染色玻璃",
    "minecraft:hard_pink_stained_glass_pane":"硬粉红色染色玻璃板",
    "minecraft:hard_purple_stained_glass":"硬紫色染色玻璃",
    "minecraft:hard_purple_stained_glass_pane":"硬紫色染色玻璃板",
    "minecraft:hard_red_stained_glass":"硬红色染色玻璃",
    "minecraft:hard_red_stained_glass_pane":"硬红色染色玻璃板",
    "minecraft:hard_white_stained_glass":"硬白色染色玻璃",
    "minecraft:hard_white_stained_glass_pane":"硬白色染色玻璃板",
    "minecraft:hard_yellow_stained_glass":"硬黄色染色玻璃",
    "minecraft:hard_yellow_stained_glass_pane":"硬黄色染色玻璃板",
    "minecraft:hardened_clay":"硬化粘土",
    "minecraft:hay_block":"干草块",
    "minecraft:heavy_core":"重型核心",
    "minecraft:heavy_weighted_pressure_plate":"重型压力板",
    "minecraft:honey_block":"蜂蜜块",
    "minecraft:honeycomb_block":"蜂窝块",
    "minecraft:hopper":"漏斗",
    "minecraft:horn_coral":"角珊瑚",
    "minecraft:horn_coral_block":"角珊瑚块",
    "minecraft:horn_coral_fan":"角珊瑚扇",
    "minecraft:horn_coral_wall_fan":"墙上的角珊瑚扇",
    "minecraft:ice":"冰",
    "minecraft:infested_chiseled_stone_bricks":"虫蚀錾制石砖",
    "minecraft:infested_cobblestone":"虫蚀圆石",
    "minecraft:infested_cracked_stone_bricks":"虫蚀裂开石砖",
    "minecraft:infested_deepslate":"虫蚀深层石材",
    "minecraft:infested_mossy_stone_bricks":"虫蚀苔石砖",
    "minecraft:infested_stone":"虫蚀石头",
    "minecraft:infested_stone_bricks":"虫蚀石砖",
    "minecraft:info_update":"信息更新",
    "minecraft:info_update2":"信息更新2",
    "minecraft:invisible_bedrock":"隐形基岩",
    "minecraft:iron_bars":"铁栏杆",
    "minecraft:iron_block":"铁块",
    "minecraft:iron_door":"铁门",
    "minecraft:iron_ore":"铁矿石",
    "minecraft:iron_trapdoor":"铁活板门",
    "minecraft:jigsaw":"拼图方块",
    "minecraft:jukebox":"唱片机",
    "minecraft:jungle_button":"丛林木按钮",
    "minecraft:jungle_door":"丛林木门",
    "minecraft:jungle_double_slab":"丛林木双重台阶",
    "minecraft:jungle_fence":"丛林木栅栏",
    "minecraft:jungle_fence_gate":"丛林木栅栏门",
    "minecraft:jungle_hanging_sign":"丛林木悬挂告示牌",
    "minecraft:jungle_leaves":"丛林木树叶",
    "minecraft:jungle_log":"丛林木原木",
    "minecraft:jungle_planks":"丛林木木板",
    "minecraft:jungle_pressure_plate":"丛林木压力板",
    "minecraft:jungle_sapling":"丛林木树苗",
    "minecraft:jungle_slab":"丛林木台阶",
    "minecraft:jungle_stairs":"丛林木楼梯",
    "minecraft:jungle_standing_sign":"丛林木立式告示牌",
    "minecraft:jungle_trapdoor":"丛林木活板门",
    "minecraft:jungle_wall_sign":"丛林木墙挂告示牌",
    "minecraft:jungle_wood":"丛林木",
    "minecraft:kelp":"海带",
    "minecraft:lab_table":"实验台",
    "minecraft:ladder":"梯子",
    "minecraft:lantern":"灯笼",
    "minecraft:lapis_block":"青金石块",
    "minecraft:lapis_ore":"青金石矿石",
    "minecraft:large_amethyst_bud":"大型紫水晶芽",
    "minecraft:large_fern":"大型蕨类植物",
    "minecraft:lava":"岩浆",
    "minecraft:lectern":"讲台",
    "minecraft:lever":"拉杆",
    "minecraft:light_block_0":"光源方块0",
    "minecraft:light_block_1":"光源方块1",
    "minecraft:light_block_10":"光源方块10",
    "minecraft:light_block_11":"光源方块11",
    "minecraft:light_block_12":"光源方块12",
    "minecraft:light_block_13":"光源方块13",
    "minecraft:light_block_14":"光源方块14",
    "minecraft:light_block_15":"光源方块15",
    "minecraft:light_block_2":"光源方块2",
    "minecraft:light_block_3":"光源方块3",
    "minecraft:light_block_4":"光源方块4",
    "minecraft:light_block_5":"光源方块5",
    "minecraft:light_block_6":"光源方块6",
    "minecraft:light_block_7":"光源方块7",
    "minecraft:light_block_8":"光源方块8",
    "minecraft:light_block_9":"光源方块9",
    "minecraft:light_blue_candle":"淡蓝色蜡烛",
    "minecraft:light_blue_candle_cake":"淡蓝色蜡烛蛋糕",
    "minecraft:light_blue_carpet":"淡蓝色地毯",
    "minecraft:light_blue_concrete":"淡蓝色混凝土",
    "minecraft:light_blue_concrete_powder":"淡蓝色混凝土粉末",
    "minecraft:light_blue_glazed_terracotta":"淡蓝色带釉陶瓦",
    "minecraft:light_blue_shulker_box":"淡蓝色潜影盒",
    "minecraft:light_blue_stained_glass":"淡蓝色染色玻璃",
    "minecraft:light_blue_stained_glass_pane":"淡蓝色染色玻璃板",
    "minecraft:light_blue_terracotta":"淡蓝色陶瓦",
    "minecraft:light_blue_wool":"淡蓝色羊毛",
    "minecraft:light_gray_candle":"浅灰色蜡烛",
    "minecraft:light_gray_candle_cake":"浅灰色蜡烛蛋糕",
    "minecraft:light_gray_carpet":"浅灰色地毯",
    "minecraft:light_gray_concrete":"浅灰色混凝土",
    "minecraft:light_gray_concrete_powder":"浅灰色混凝土粉末",
    "minecraft:light_gray_shulker_box":"浅灰色潜影盒",
    "minecraft:light_gray_stained_glass":"浅灰色染色玻璃",
    "minecraft:light_gray_stained_glass_pane":"浅灰色染色玻璃板",
    "minecraft:light_gray_terracotta":"浅灰色陶瓦",
    "minecraft:light_gray_wool":"浅灰色羊毛",
    "minecraft:light_weighted_pressure_plate":"轻质压力板",
    "minecraft:lightning_rod":"避雷针",
    "minecraft:lilac":"丁香",
    "minecraft:lily_of_the_valley":"铃兰",
    "minecraft:lime_candle":"黄绿色蜡烛",
    "minecraft:lime_candle_cake":"黄绿色蜡烛蛋糕",
    "minecraft:lime_carpet":"黄绿色地毯",
    "minecraft:lime_concrete":"黄绿色混凝土",
    "minecraft:lime_concrete_powder":"黄绿色混凝土粉末",
    "minecraft:lime_glazed_terracotta":"黄绿色带釉陶瓦",
    "minecraft:lime_shulker_box":"黄绿色潜影盒",
    "minecraft:lime_stained_glass":"黄绿色染色玻璃",
    "minecraft:lime_stained_glass_pane":"黄绿色染色玻璃板",
    "minecraft:lime_terracotta":"黄绿色陶瓦",
    "minecraft:lime_wool":"黄绿色羊毛",
    "minecraft:lit_blast_furnace":"点燃的高炉",
    "minecraft:lit_deepslate_redstone_ore":"点燃的深层红石矿石",
    "minecraft:lit_furnace":"点燃的熔炉",
    "minecraft:lit_pumpkin":"点燃的南瓜",
    "minecraft:lit_redstone_lamp":"点燃的红石灯",
    "minecraft:lit_redstone_ore":"点燃的红石矿石",
    "minecraft:lit_smoker":"点燃的烟熏炉",
    "minecraft:lodestone":"磁石",
    "minecraft:loom":"织布机",
    "minecraft:magenta_candle":"品红色蜡烛",
    "minecraft:magenta_candle_cake":"品红色蜡烛蛋糕",
    "minecraft:magenta_carpet":"品红色地毯",
    "minecraft:magenta_concrete":"品红色混凝土",
    "minecraft:magenta_concrete_powder":"品红色混凝土粉末",
    "minecraft:magenta_glazed_terracotta":"品红色带釉陶瓦",
    "minecraft:magenta_shulker_box":"品红色潜影盒",
    "minecraft:magenta_stained_glass":"品红色染色玻璃",
    "minecraft:magenta_stained_glass_pane":"品红色染色玻璃板",
    "minecraft:magenta_terracotta":"品红色陶瓦",
    "minecraft:magenta_wool":"品红色羊毛",
    "minecraft:magma":"熔岩",
    "minecraft:mangrove_button":"红树林木按钮",
    "minecraft:mangrove_door":"红树林门",
    "minecraft:mangrove_double_slab":"红树林木双重台阶",
    "minecraft:mangrove_fence":"红树林木栅栏",
    "minecraft:mangrove_fence_gate":"红树林木栅栏门",
    "minecraft:mangrove_hanging_sign":"红树林木悬挂告示牌",
    "minecraft:mangrove_leaves":"红树林木树叶",
    "minecraft:mangrove_log":"红树林木原木",
    "minecraft:mangrove_planks":"红树林木木板",
    "minecraft:mangrove_pressure_plate":"红树林木压力板",
    "minecraft:mangrove_propagule":"红树林木种子",
    "minecraft:mangrove_propagule_hanging":"悬挂的红树林木种子",
    "minecraft:mangrove_roots":"红树林木根",
    "minecraft:mangrove_slab":"红树林木台阶",
    "minecraft:mangrove_stairs":"红树林木楼梯",
    "minecraft:mangrove_standing_sign":"红树林木立式告示牌",
    "minecraft:mangrove_trapdoor":"红树林木活板门",
    "minecraft:mangrove_wall_sign":"红树林木墙挂告示牌",
    "minecraft:mangrove_wood":"红树林木",
    "minecraft:material_reducer":"材料减少器",
    "minecraft:medium_amethyst_bud":"中型紫水晶芽",
    "minecraft:melon_block":"南瓜块",
    "minecraft:melon_stem":"南瓜梗",
    "minecraft:mob_spawner":"生物刷怪箱",
    "minecraft:moss_block":"苔藓块",
    "minecraft:moss_carpet":"苔藓地毯",
    "minecraft:mossy_cobblestone":"苔石",
    "minecraft:mossy_cobblestone_double_slab":"苔石双重台阶",
    "minecraft:mossy_cobblestone_slab":"苔石台阶",
    "minecraft:mossy_cobblestone_stairs":"苔石楼梯",
    "minecraft:mossy_cobblestone_wall":"苔石墙",
    "minecraft:mossy_stone_brick_double_slab":"苔石砖双重台阶",
    "minecraft:mossy_stone_brick_slab":"苔石砖台阶",
    "minecraft:mossy_stone_brick_stairs":"苔石砖楼梯",
    "minecraft:mossy_stone_brick_wall":"苔石砖墙",
    "minecraft:moving_block":"移动的方块",
    "minecraft:mud":"泥",
    "minecraft:mud_brick_double_slab":"泥砖双重台阶",
    "minecraft:mud_brick_slab":"泥砖台阶",
    "minecraft:mud_brick_stairs":"泥砖楼梯",
    "minecraft:mud_brick_wall":"泥砖墙",
    "minecraft:mud_bricks":"泥砖",
    "minecraft:muddy_mangrove_roots":"泥泞的红树林木根",
    "minecraft:mycelium":"菌丝体",
    "minecraft:nether_brick":"下界砖",
    "minecraft:nether_brick_double_slab":"下界砖双重台阶",
    "minecraft:nether_brick_fence":"下界砖栅栏",
    "minecraft:nether_brick_slab":"下界砖台阶",
    "minecraft:nether_brick_stairs":"下界砖楼梯",
    "minecraft:nether_brick_wall":"下界砖墙",
    "minecraft:nether_gold_ore":"下界金矿石",
    "minecraft:nether_sprouts":"下界苗",
    "minecraft:nether_wart":"下界疣",
    "minecraft:nether_wart_block":"下界疣块",
    "minecraft:netherite_block":"下界合金块",
    "minecraft:netherrack":"下界岩",
    "minecraft:netherreactor":"下界反应堆",
    "minecraft:normal_stone_double_slab":"普通石头双重台阶",
    "minecraft:normal_stone_slab":"普通石头台阶",
    "minecraft:normal_stone_stairs":"普通石头楼梯",
    "minecraft:noteblock":"音符盒",
    "minecraft:oak_double_slab":"橡木双重台阶",
    "minecraft:oak_fence":"橡木栅栏",
    "minecraft:oak_hanging_sign":"橡木悬挂告示牌",
    "minecraft:oak_leaves":"橡木树叶",
    "minecraft:oak_log":"橡木原木",
    "minecraft:oak_planks":"橡木木板",
    "minecraft:oak_sapling":"橡木树苗",
    "minecraft:oak_slab":"橡木台阶",
    "minecraft:oak_stairs":"橡木楼梯",
    "minecraft:oak_wood":"橡木",
    "minecraft:observer":"观察者",
    "minecraft:obsidian":"黑曜石",
    "minecraft:ochre_froglight":"赭色蛙光",
    "minecraft:orange_candle":"橙色蜡烛",
    "minecraft:orange_candle_cake":"橙色蜡烛蛋糕",
    "minecraft:orange_carpet":"橙色地毯",
    "minecraft:orange_concrete":"橙色混凝土",
    "minecraft:orange_concrete_powder":"橙色混凝土粉末",
    "minecraft:orange_glazed_terracotta":"橙色带釉陶瓦",
    "minecraft:orange_shulker_box":"橙色潜影盒",
    "minecraft:orange_stained_glass":"橙色染色玻璃",
    "minecraft:orange_stained_glass_pane":"橙色染色玻璃板",
    "minecraft:orange_terracotta":"橙色陶瓦",
    "minecraft:orange_wool":"橙色羊毛",
    "minecraft:oxidized_chiseled_copper":"氧化的錾制铜块",
    "minecraft:oxidized_copper":"氧化的铜块",
    "minecraft:oxidized_copper_bulb":"氧化的铜质灯泡",
    "minecraft:oxidized_copper_door":"氧化的铜门",
    "minecraft:oxidized_copper_grate":"氧化的铜质格栅",
    "minecraft:oxidized_copper_trapdoor":"氧化的铜活板门",
    "minecraft:oxidized_cut_copper":"氧化的切割铜块",
    "minecraft:oxidized_cut_copper_slab":"氧化的切割铜台阶",
    "minecraft:oxidized_cut_copper_stairs":"氧化的切割铜楼梯",
    "minecraft:oxidized_double_cut_copper_slab":"氧化的双重切割铜台阶",
    "minecraft:packed_ice":"浮冰",
    "minecraft:packed_mud":"泥坯",
    "minecraft:pearlescent_froglight":"珍珠色蛙光",
    "minecraft:petrified_oak_double_slab":"石化橡木双重台阶",
    "minecraft:peony":"牡丹",
    "minecraft:petrified_oak_slab":"石化橡木台阶",
    "minecraft:pink_candle":"粉红色蜡烛",
    "minecraft:pink_candle_cake":"粉红色蜡烛蛋糕",
    "minecraft:pink_carpet":"粉红色地毯",
    "minecraft:pink_concrete":"粉红色混凝土",
    "minecraft:pink_concrete_powder":"粉红色混凝土粉末",
    "minecraft:pink_glazed_terracotta":"粉红色带釉陶瓦",
    "minecraft:pink_petals":"粉色花瓣",
    "minecraft:pink_shulker_box":"粉红色潜影盒",
    "minecraft:pink_stained_glass":"粉红色染色玻璃",
    "minecraft:pink_stained_glass_pane":"粉红色染色玻璃板",
    "minecraft:pink_terracotta":"粉红色陶瓦",
    "minecraft:pink_wool":"粉红色羊毛",
    "minecraft:piston":"活塞",
    "minecraft:piston_arm_collision":"活塞臂碰撞",
    "minecraft:pitcher_crop":"瓶子草",
    "minecraft:pitcher_plant":"瓶子植物",
    "minecraft:podzol":"灰化土",
    "minecraft:pointed_dripstone":"尖顶滴水石",
    "minecraft:polished_andesite":"磨制安山岩",
    "minecraft:polished_andesite_double_slab":"磨制安山岩双重台阶",
    "minecraft:polished_andesite_slab":"磨制安山岩台阶",
    "minecraft:polished_andesite_stairs":"磨制安山岩楼梯",
    "minecraft:polished_basalt":"磨制玄武岩",
    "minecraft:polished_blackstone":"磨制黑石",
    "minecraft:polished_blackstone_brick_double_slab":"磨制黑石砖双重台阶",
    "minecraft:polished_blackstone_brick_slab":"磨制黑石砖台阶",
    "minecraft:polished_blackstone_brick_stairs":"磨制黑石砖楼梯",
    "minecraft:polished_blackstone_brick_wall":"磨制黑石砖墙",
    "minecraft:polished_blackstone_bricks":"磨制黑石砖",
    "minecraft:polished_blackstone_button":"磨制黑石按钮",
    "minecraft:polished_blackstone_double_slab":"磨制黑石双重台阶",
    "minecraft:polished_blackstone_pressure_plate":"磨制黑石压力板",
    "minecraft:polished_blackstone_slab":"磨制黑石台阶",
    "minecraft:polished_blackstone_stairs":"磨制黑石楼梯",
    "minecraft:polished_blackstone_wall":"磨制黑石墙",
    "minecraft:polished_deepslate":"磨制深层石材",
    "minecraft:polished_deepslate_double_slab":"磨制深层石材双重台阶",
    "minecraft:polished_deepslate_slab":"磨制深层石材台阶",
    "minecraft:polished_deepslate_stairs":"磨制深层石材楼梯",
    "minecraft:polished_deepslate_wall":"磨制深层石材墙",
    "minecraft:polished_diorite":"磨制闪长岩",
    "minecraft:polished_diorite_double_slab":"磨制闪长岩双重台阶",
    "minecraft:polished_diorite_slab":"磨制闪长岩台阶",
    "minecraft:polished_diorite_stairs":"磨制闪长岩楼梯",
    "minecraft:polished_granite":"磨制花岗岩",
    "minecraft:polished_granite_double_slab":"磨制花岗岩双重台阶",
    "minecraft:polished_granite_slab":"磨制花岗岩台阶",
    "minecraft:polished_granite_stairs":"磨制花岗岩楼梯",
    "minecraft:polished_tuff":"磨制凝灰岩",
    "minecraft:polished_tuff_double_slab":"磨制凝灰岩双重台阶",
    "minecraft:polished_tuff_slab":"磨制凝灰岩台阶",
    "minecraft:polished_tuff_stairs":"磨制凝灰岩楼梯",
    "minecraft:polished_tuff_wall":"磨制凝灰岩墙",
    "minecraft:portal":"传送门",
    "minecraft:potatoes":"土豆",
    "minecraft:powder_snow":"粉末雪",
    "minecraft:powered_comparator":"激活的比较器",
    "minecraft:powered_repeater":"激活的中继器",
    "minecraft:prismarine":"海晶石",
    "minecraft:prismarine_brick_double_slab":"海晶石砖双重台阶",
    "minecraft:prismarine_brick_slab":"海晶石砖台阶",
    "minecraft:prismarine_bricks":"海晶石砖",
    "minecraft:prismarine_bricks_stairs":"海晶石砖楼梯",
    "minecraft:prismarine_double_slab":"海晶石双重台阶",
    "minecraft:prismarine_slab":"海晶石台阶",
    "minecraft:prismarine_stairs":"海晶石楼梯",
    "minecraft:prismarine_wall":"海晶石墙",
    "minecraft:pumpkin":"南瓜",
    "minecraft:pumpkin_stem":"南瓜梗",
    "minecraft:purple_candle":"紫色蜡烛",
    "minecraft:purple_candle_cake":"紫色蜡烛蛋糕",
    "minecraft:purple_carpet":"紫色地毯",
    "minecraft:purple_concrete":"紫色混凝土",
    "minecraft:purple_concrete_powder":"紫色混凝土粉末",
    "minecraft:purple_glazed_terracotta":"紫色带釉陶瓦",
    "minecraft:purple_shulker_box":"紫色潜影盒",
    "minecraft:purple_stained_glass":"紫色染色玻璃",
    "minecraft:purple_stained_glass_pane":"紫色染色玻璃板",
    "minecraft:purple_terracotta":"紫色陶瓦",
    "minecraft:purple_wool":"紫色羊毛",
    "minecraft:purpur_block":"紫珀块",
    "minecraft:purpur_pillar":"紫珀柱",
    "minecraft:purpur_double_slab":"紫珀双重台阶",
    "minecraft:purpur_slab":"紫珀台阶",
    "minecraft:purpur_stairs":"紫珀楼梯",
    "minecraft:quartz_block":"石英块",
    "minecraft:quartz_bricks":"石英砖",
    "minecraft:quartz_double_slab":"石英双重台阶",
    "minecraft:quartz_ore":"石英矿石",
    "minecraft:quartz_pillar":"石英柱",
    "minecraft:quartz_slab":"石英台阶",
    "minecraft:quartz_stairs":"石英楼梯",
    "minecraft:rail":"铁轨",
    "minecraft:raw_copper_block":"原始铜块",
    "minecraft:raw_gold_block":"原始金块",
    "minecraft:raw_iron_block":"原始铁块",
    "minecraft:red_candle":"红色蜡烛",
    "minecraft:red_candle_cake":"红色蜡烛蛋糕",
    "minecraft:red_carpet":"红色地毯",
    "minecraft:red_concrete":"红色混凝土",
    "minecraft:red_concrete_powder":"红色混凝土粉末",
    "minecraft:red_flower":"红色花朵",
    "minecraft:red_glazed_terracotta":"红色带釉陶瓦",
    "minecraft:red_mushroom":"红色蘑菇",
    "minecraft:red_mushroom_block":"红色蘑菇块",
    "minecraft:red_nether_brick":"红色下界砖",
    "minecraft:red_nether_brick_double_slab":"红色下界砖双重台阶",
    "minecraft:red_nether_brick_slab":"红色下界砖台阶",
    "minecraft:red_nether_brick_stairs":"红色下界砖楼梯",
    "minecraft:red_nether_brick_wall":"红色下界砖墙",
    "minecraft:red_sand":"红沙",
    "minecraft:red_sandstone":"红沙石",
    "minecraft:red_sandstone_double_slab":"红沙石双重台阶",
    "minecraft:red_sandstone_slab":"红沙石台阶",
    "minecraft:red_sandstone_stairs":"红沙石楼梯",
    "minecraft:red_sandstone_wall":"红沙石墙",
    "minecraft:red_shulker_box":"红色潜影盒",
    "minecraft:red_stained_glass":"红色染色玻璃",
    "minecraft:red_stained_glass_pane":"红色染色玻璃板",
    "minecraft:red_terracotta":"红色陶瓦",
    "minecraft:red_wool":"红色羊毛",
    "minecraft:redstone_block":"红石块",
    "minecraft:redstone_lamp":"红石灯",
    "minecraft:redstone_ore":"红石矿石",
    "minecraft:redstone_torch":"红石火把",
    "minecraft:redstone_wire":"红石线",
    "minecraft:reeds":"甘蔗",
    "minecraft:reinforced_deepslate":"强化深层石材",
    "minecraft:repeating_command_block":"重复命令方块",
    "minecraft:reserved6":"保留6",
    "minecraft:respawn_anchor":"重生锚",
    "minecraft:rose_bush":"玫瑰丛",
    "minecraft:sand":"沙子",
    "minecraft:sandstone":"沙石",
    "minecraft:sandstone_double_slab":"沙石双重台阶",
    "minecraft:sandstone_slab":"沙石台阶",
    "minecraft:sandstone_stairs":"沙石楼梯",
    "minecraft:sandstone_wall":"沙石墙",
    "minecraft:scaffolding":"脚手架",
    "minecraft:sculk":"潜声",
    "minecraft:sculk_catalyst":"潜声催化剂",
    "minecraft:sculk_sensor":"潜声传感器",
    "minecraft:sculk_shrieker":"潜声尖叫者",
    "minecraft:sculk_vein":"潜声矿脉",
    "minecraft:sea_lantern":"海洋灯笼",
    "minecraft:sea_pickle":"海泡菜",
    "minecraft:seagrass":"海草",
    "minecraft:short_grass":"短草",
    "minecraft:shroomlight":"蘑菇灯",
    "minecraft:silver_glazed_terracotta":"银色带釉陶瓦",
    "minecraft:skull":"头骨",
    "minecraft:slime":"史莱姆",
    "minecraft:small_amethyst_bud":"小型紫水晶芽",
    "minecraft:small_dripleaf_block":"小型滴水叶块",
    "minecraft:smithing_table":"锻造台",
    "minecraft:smoker":"烟熏炉",
    "minecraft:smooth_basalt":"光滑玄武岩",
    "minecraft:smooth_quartz":"光滑石英",
    "minecraft:smooth_quartz_double_slab":"光滑石英双重台阶",
    "minecraft:smooth_quartz_slab":"光滑石英台阶",
    "minecraft:smooth_quartz_stairs":"光滑石英楼梯",
    "minecraft:smooth_red_sandstone":"光滑红沙石",
    "minecraft:smooth_red_sandstone_double_slab":"光滑红沙石双重台阶",
    "minecraft:smooth_red_sandstone_slab":"光滑红沙石台阶",
    "minecraft:smooth_red_sandstone_stairs":"光滑红沙石楼梯",
    "minecraft:smooth_sandstone":"光滑沙石",
    "minecraft:smooth_sandstone_double_slab":"光滑沙石双重台阶",
    "minecraft:smooth_sandstone_slab":"光滑沙石台阶",
    "minecraft:smooth_sandstone_stairs":"光滑沙石楼梯",
    "minecraft:smooth_stone":"平滑石头",
    "minecraft:smooth_stone_double_slab":"平滑石头双重台阶",
    "minecraft:smooth_stone_slab":"平滑石头台阶",
    "minecraft:sniffer_egg":"嗅探蛋",
    "minecraft:snow":"雪",
    "minecraft:snow_layer":"雪层",
    "minecraft:soul_campfire":"灵魂篝火",
    "minecraft:soul_fire":"灵魂火",
    "minecraft:soul_lantern":"灵魂灯笼",
    "minecraft:soul_sand":"灵魂沙",
    "minecraft:soul_soil":"灵魂土壤",
    "minecraft:soul_torch":"灵魂火把",
    "minecraft:sponge":"海绵",
    "minecraft:spore_blossom":"孢子花",
    "minecraft:spruce_button":"云杉木按钮",
    "minecraft:spruce_door":"云杉门",
    "minecraft:spruce_double_slab":"云杉木双重台阶",
    "minecraft:spruce_fence":"云杉木栅栏",
    "minecraft:spruce_fence_gate":"云杉木栅栏门",
    "minecraft:spruce_hanging_sign":"云杉木悬挂告示牌",
    "minecraft:spruce_leaves":"云杉木树叶",
    "minecraft:spruce_log":"云杉木原木",
    "minecraft:spruce_planks":"云杉木木板",
    "minecraft:spruce_pressure_plate":"云杉木压力板",
    "minecraft:spruce_sapling":"云杉木树苗",
    "minecraft:spruce_slab":"云杉木台阶",
    "minecraft:spruce_stairs":"云杉木楼梯",
    "minecraft:spruce_standing_sign":"云杉木立式告示牌",
    "minecraft:spruce_trapdoor":"云杉木活板门",
    "minecraft:spruce_wall_sign":"云杉木墙挂告示牌",
    "minecraft:spruce_wood":"云杉木",
    "minecraft:standing_banner":"直立的旗帜",
    "minecraft:standing_sign":"立式告示牌",
    "minecraft:sticky_piston":"粘性活塞",
    "minecraft:sticky_piston_arm_collision":"粘性活塞臂碰撞",
    "minecraft:stone":"石头",
    "minecraft:stone_block_slab":"石头方块台阶",
    "minecraft:minecraft:stone_brick_double_slab":"石砖双重台阶",
    "minecraft:stone_block_slab2":"石头方块台阶2",
    "minecraft:stone_block_slab3":"石头方块台阶3",
    "minecraft:stone_block_slab4":"石头方块台阶4",
    "minecraft:stone_brick_double_slab":"石砖双重台阶",
    "minecraft:stone_brick_slab":"石砖台阶",
    "minecraft:stone_brick_stairs":"石砖楼梯",
    "minecraft:stone_brick_wall":"石砖墙",
    "minecraft:stone_button":"石按钮",
    "minecraft:stone_pressure_plate":"石压力板",
    "minecraft:stone_stairs":"石楼梯",
    "minecraft:stonecutter":"石头切割机",
    "minecraft:stonecutter_block":"石头切割机方块",
    "minecraft:stripped_acacia_log":"去皮的金合欢木原木",
    "minecraft:stripped_acacia_wood":"去皮的金合欢木",
    "minecraft:stripped_bamboo_block":"去皮的竹块",
    "minecraft:stripped_birch_log":"去皮的白桦木原木",
    "minecraft:stripped_birch_wood":"去皮的白桦木",
    "minecraft:stripped_cherry_log":"去皮的樱花木原木",
    "minecraft:stripped_cherry_wood":"去皮的樱花木",
    "minecraft:stripped_crimson_hyphae":"去皮的绯红菌柄",
    "minecraft:stripped_crimson_stem":"去皮的绯红茎",
    "minecraft:stripped_dark_oak_log":"去皮的深色橡木原木",
    "minecraft:stripped_dark_oak_wood":"去皮的深色橡木",
    "minecraft:stripped_jungle_log":"去皮的丛林木原木",
    "minecraft:stripped_jungle_wood":"去皮的丛林木",
    "minecraft:stripped_mangrove_log":"去皮的红树林木原木",
    "minecraft:stripped_mangrove_wood":"去皮的红树林木",
    "minecraft:stripped_oak_log":"去皮的橡木原木",
    "minecraft:stripped_oak_wood":"去皮的橡木",
    "minecraft:stripped_spruce_log":"去皮的云杉木原木",
    "minecraft:stripped_spruce_wood":"去皮的云杉木",
    "minecraft:stripped_warped_hyphae":"去皮的诡异菌柄",
    "minecraft:stripped_warped_stem":"去皮的诡异茎",
    "minecraft:structure_block":"结构方块",
    "minecraft:structure_void":"结构空位",
    "minecraft:sunflower":"向日葵",
    "minecraft:suspicious_gravel":"可疑的沙砾",
    "minecraft:suspicious_sand":"可疑的沙子",
    "minecraft:sweet_berry_bush":"甜浆果丛",
    "minecraft:tall_grass":"高草",
    "minecraft:target":"靶心",
    "minecraft:tinted_glass":"着色玻璃",
    "minecraft:tnt":"炸药",
    "minecraft:torch":"火把",
    "minecraft:torchflower":"火把花",
    "minecraft:torchflower_crop":"火把花作物",
    "minecraft:trapdoor":"活板门",
    "minecraft:trapped_chest":"陷阱箱子",
    "minecraft:trial_spawner":"试验用生物刷怪箱",
    "minecraft:trip_wire":"绊线",
    "minecraft:tripwire_hook":"绊线钩",
    "minecraft:tube_coral":"管珊瑚",
    "minecraft:tube_coral_block":"管珊瑚块",
    "minecraft:tube_coral_fan":"管珊瑚扇",
    "minecraft:tube_coral_wall_fan":"墙上的管珊瑚扇",
    "minecraft:tuff":"凝灰岩",
    "minecraft:tuff_brick_double_slab":"凝灰岩砖双重台阶",
    "minecraft:tuff_brick_slab":"凝灰岩砖台阶",
    "minecraft:tuff_brick_stairs":"凝灰岩砖楼梯",
    "minecraft:tuff_brick_wall":"凝灰岩砖墙",
    "minecraft:tuff_bricks":"凝灰岩砖",
    "minecraft:tuff_double_slab":"凝灰岩双重台阶",
    "minecraft:tuff_slab":"凝灰岩台阶",
    "minecraft:tuff_stairs":"凝灰岩楼梯",
    "minecraft:tuff_wall":"凝灰岩墙",
    "minecraft:turtle_egg":"海龟蛋",
    "minecraft:twisting_vines":"缠绕藤蔓",
    "minecraft:underwater_tnt":"水下炸药",
    "minecraft:underwater_torch":"水下火把",
    "minecraft:undyed_shulker_box":"未染色潜影盒",
    "minecraft:unknown":"未知",
    "minecraft:unlit_redstone_torch":"未点燃的红石火把",
    "minecraft:unpowered_comparator":"未激活的比较器",
    "minecraft:unpowered_repeater":"未激活的中继器",
    "minecraft:vault":"金库",
    "minecraft:verdant_froglight":"翠绿蛙光",
    "minecraft:vine":"藤蔓",
    "minecraft:wall_banner":"墙挂旗帜",
    "minecraft:wall_sign":"墙挂告示牌",
    "minecraft:warped_button":"诡异按钮",
    "minecraft:warped_door":"诡异门",
    "minecraft:warped_double_slab":"诡异双重台阶",
    "minecraft:warped_fence":"诡异栅栏",
    "minecraft:warped_fence_gate":"诡异栅栏门",
    "minecraft:warped_fungus":"诡异菌",
    "minecraft:warped_hanging_sign":"诡异悬挂告示牌",
    "minecraft:warped_hyphae":"诡异菌柄",
    "minecraft:warped_nylium":"诡异下界菌岩",
    "minecraft:warped_planks":"诡异木木板",
    "minecraft:warped_pressure_plate":"诡异木压力板",
    "minecraft:warped_roots":"诡异根",
    "minecraft:warped_slab":"诡异木台阶",
    "minecraft:warped_stairs":"诡异木楼梯",
    "minecraft:warped_standing_sign":"诡异木立式告示牌",
    "minecraft:warped_stem":"诡异茎",
    "minecraft:warped_trapdoor":"诡异木活板门",
    "minecraft:warped_wall_sign":"诡异木墙挂告示牌",
    "minecraft:warped_wart_block":"诡异疣块",
    "minecraft:water":"水",
    "minecraft:waterlily":"睡莲",
    "minecraft:waxed_chiseled_copper":"上蜡的錾制铜块",
    "minecraft:waxed_copper":"上蜡的铜块",
    "minecraft:waxed_copper_bulb":"上蜡的铜质灯泡",
    "minecraft:waxed_copper_door":"上蜡的铜门",
    "minecraft:waxed_copper_grate":"上蜡的铜质格栅",
    "minecraft:waxed_copper_trapdoor":"上蜡的铜活板门",
    "minecraft:waxed_cut_copper":"上蜡的切割铜块",
    "minecraft:waxed_cut_copper_slab":"上蜡的切割铜台阶",
    "minecraft:waxed_cut_copper_stairs":"上蜡的切割铜楼梯",
    "minecraft:waxed_double_cut_copper_slab":"上蜡的双重切割铜台阶",
    "minecraft:waxed_exposed_chiseled_copper":"上蜡的暴露錾制铜块",
    "minecraft:waxed_exposed_copper":"上蜡的暴露铜块",
    "minecraft:waxed_exposed_copper_bulb":"上蜡的暴露铜质灯泡",
    "minecraft:waxed_exposed_copper_door":"上蜡的暴露铜门",
    "minecraft:waxed_exposed_copper_grate":"上蜡的暴露铜质格栅",
    "minecraft:waxed_exposed_copper_trapdoor":"上蜡的暴露铜活板门",
    "minecraft:waxed_exposed_cut_copper":"上蜡的暴露切割铜块",
    "minecraft:waxed_exposed_cut_copper_slab":"上蜡的暴露切割铜台阶",
    "minecraft:waxed_exposed_cut_copper_stairs":"上蜡的暴露切割铜楼梯",
    "minecraft:waxed_exposed_double_cut_copper_slab":"上蜡的暴露双重切割铜台阶",
    "minecraft:waxed_oxidized_chiseled_copper":"上蜡的氧化錾制铜块",
    "minecraft:waxed_oxidized_copper":"上蜡的氧化铜块",
    "minecraft:waxed_oxidized_copper_bulb":"上蜡的氧化铜质灯泡",
    "minecraft:waxed_oxidized_copper_door":"上蜡的氧化铜门",
    "minecraft:waxed_oxidized_copper_grate":"上蜡的氧化铜质格栅",
    "minecraft:waxed_oxidized_copper_trapdoor":"上蜡的氧化铜活板门",
    "minecraft:waxed_oxidized_cut_copper":"上蜡的氧化切割铜块",
    "minecraft:waxed_oxidized_cut_copper_slab":"上蜡的氧化切割铜台阶",
    "minecraft:waxed_oxidized_cut_copper_stairs":"上蜡的氧化切割铜楼梯",
    "minecraft:waxed_oxidized_double_cut_copper_slab":"上蜡的氧化双重切割铜台阶",
    "minecraft:waxed_weathered_chiseled_copper":"上蜡的风化錾制铜块",
    "minecraft:waxed_weathered_copper":"上蜡的风化铜块",
    "minecraft:waxed_weathered_copper_bulb":"上蜡的风化铜质灯泡",
    "minecraft:waxed_weathered_copper_door":"上蜡的风化铜门",
    "minecraft:waxed_weathered_copper_grate":"上蜡的风化铜质格栅",
    "minecraft:waxed_weathered_copper_trapdoor":"上蜡的风化铜活板门",
    "minecraft:waxed_weathered_cut_copper":"上蜡的风化切割铜块",
    "minecraft:waxed_weathered_cut_copper_slab":"上蜡的风化切割铜台阶",
    "minecraft:waxed_weathered_cut_copper_stairs":"上蜡的风化切割铜楼梯",
    "minecraft:waxed_weathered_double_cut_copper_slab":"上蜡的风化双重切割铜台阶",
    "minecraft:weathered_chiseled_copper":"风化的錾制铜块",
    "minecraft:weathered_copper":"风化的铜块",
    "minecraft:weathered_copper_bulb":"风化的铜质灯泡",
    "minecraft:weathered_copper_door":"风化的铜门",
    "minecraft:weathered_copper_grate":"风化的铜质格栅",
    "minecraft:weathered_copper_trapdoor":"风化的铜活板门",
    "minecraft:weathered_cut_copper":"风化的切割铜块",
    "minecraft:weathered_cut_copper_slab":"风化的切割铜台阶",
    "minecraft:weathered_cut_copper_stairs":"风化的切割铜楼梯",
    "minecraft:weathered_double_cut_copper_slab":"风化的双重切割铜台阶",
    "minecraft:web":"蜘蛛网",
    "minecraft:weeping_vines":"哭泣藤蔓",
    "minecraft:wet_sponge":"湿海绵",
    "minecraft:wheat":"小麦",
    "minecraft:white_candle":"白色蜡烛",
    "minecraft:white_candle_cake":"白色蜡烛蛋糕",
    "minecraft:white_carpet":"白色地毯",
    "minecraft:white_concrete":"白色混凝土",
    "minecraft:white_concrete_powder":"白色混凝土粉末",
    "minecraft:white_glazed_terracotta":"白色带釉陶瓦",
    "minecraft:white_shulker_box":"白色潜影盒",
    "minecraft:white_stained_glass":"白色染色玻璃",
    "minecraft:white_stained_glass_pane":"白色染色玻璃板",
    "minecraft:white_terracotta":"白色陶瓦",
    "minecraft:white_wool":"白色羊毛",
    "minecraft:wither_rose":"凋零玫瑰",
    "minecraft:wooden_button":"木按钮",
    "minecraft:wooden_door":"木门",
    "minecraft:wooden_pressure_plate":"木压力板",
    "minecraft:yellow_candle":"黄色蜡烛",
    "minecraft:yellow_candle_cake":"黄色蜡烛蛋糕",
    "minecraft:yellow_carpet":"黄色地毯",
    "minecraft:yellow_concrete":"黄色混凝土",
    "minecraft:yellow_concrete_powder":"黄色混凝土粉末",
    "minecraft:yellow_glazed_terracotta":"黄色带釉陶瓦",
    "minecraft:yellow_shulker_box":"黄色潜影盒",
    "minecraft:yellow_stained_glass":"黄色染色玻璃",
    "minecraft:yellow_stained_glass_pane":"黄色染色玻璃板",
    "minecraft:yellow_terracotta":"黄色陶瓦",
    "minecraft:yellow_wool":"黄色羊毛",
    "实体":"##################################################",
    "minecraft:agent": "智能体",
    "minecraft:allay": "悦灵",
    "minecraft:area_effect_cloud": "区域效果云",
    "minecraft:armadillo": "犰狳",
    "minecraft:armor_stand": "盔甲架",
    "minecraft:arrow": "箭",
    "minecraft:axolotl": "美西螈",
    "minecraft:balloon": "气球",
    "minecraft:bat": "蝙蝠",
    "minecraft:bee": "蜜蜂",
    "minecraft:blaze": "烈焰人",
    "minecraft:boat": "船",
    "minecraft:bogged": "沼骸",
    "minecraft:breeze": "旋风人",
    "minecraft:breeze_wind_charge_projectile": "风弹",
    "minecraft:camel": "骆驼",
    "minecraft:cat": "猫",
    "minecraft:cave_spider": "洞穴蜘蛛",
    "minecraft:chalkboard": "黑板",
    "minecraft:chest_boat": "运输船",
    "minecraft:chest_minecart": "运输矿车",
    "minecraft:chicken": "鸡",
    "minecraft:cod": "鳕鱼",
    "minecraft:command_block_minecart": "命令方块矿车",
    "minecraft:cow": "牛",
    "minecraft:creeper": "苦力怕",
    "minecraft:dolphin": "海豚",
    "minecraft:donkey": "驴",
    "minecraft:dragon_fireball": "末影龙火球",
    "minecraft:drowned": "溺尸",
    "minecraft:egg": "鸡蛋",
    "minecraft:elder_guardian": "远古守卫者",
    "minecraft:elder_guardian_ghost": "远古守卫者幽灵",
    "minecraft:ender_crystal": "末影水晶",
    "minecraft:ender_dragon": "末影龙",
    "minecraft:ender_pearl": "末影珍珠",
    "minecraft:enderman": "末影人",
    "minecraft:endermite": "末影螨",
    "minecraft:evocation_fang": "唤魔者尖牙",
    "minecraft:evocation_illager": "唤魔者",
    "minecraft:eye_of_ender_signal": "扔出的末影之眼",
    "minecraft:falling_block": "下落的方块",
    "minecraft:fireball": "火球",
    "minecraft:fireworks_rocket": "烟花火箭",
    "minecraft:fishing_hook": "钓鱼钩",
    "minecraft:fox": "狐狸",
    "minecraft:frog": "青蛙",
    "minecraft:ghast": "恶魂",
    "minecraft:glow_squid": "发光鱿鱼",
    "minecraft:goat": "山羊",
    "minecraft:guardian": "守卫者",
    "minecraft:hoglin": "疣猪兽",
    "minecraft:hopper_minecart": "漏斗矿车",
    "minecraft:horse": "马",
    "minecraft:husk": "尸壳",
    "minecraft:ice_bomb": "冰弹",
    "minecraft:iron_golem": "铁傀儡",
    "minecraft:item": "物品",
    "minecraft:leash_knot": "拴绳",
    "minecraft:lightning_bolt": "闪电束",
    "minecraft:lingering_potion": "滞留药水",
    "minecraft:llama": "羊驼",
    "minecraft:llama_spit": "羊驼唾沫",
    "minecraft:magma_cube": "岩浆怪",
    "minecraft:minecart": "矿车",
    "minecraft:mooshroom": "哞菇",
    "minecraft:moving_block": "移动的方块",
    "minecraft:mule": "骡",
    "minecraft:npc": "minecraft:NPC",
    "minecraft:ocelot": "豹猫",
    "minecraft:ominous_item_spawner": "不祥之物生成器",
    "minecraft:painting": "画",
    "minecraft:panda": "熊猫",
    "minecraft:parrot": "鹦鹉",
    "minecraft:phantom": "幻翼",
    "minecraft:pig": "猪",
    "minecraft:piglin": "猪灵",
    "minecraft:piglin_brute": "猪灵蛮兵",
    "minecraft:pillager": "掠夺者",
    "minecraft:player": "玩家",
    "minecraft:polar_bear": "北极熊",
    "minecraft:pufferfish": "河豚",
    "minecraft:rabbit": "兔子",
    "minecraft:ravager": "劫掠兽",
    "minecraft:salmon": "鲑鱼",
    "minecraft:sheep": "羊",
    "minecraft:shield": "盾牌",
    "minecraft:shulker": "潜影贝",
    "minecraft:shulker_bullet": "潜影弹",
    "minecraft:silverfish": "蠹虫",
    "minecraft:skeleton": "骷髅",
    "minecraft:skeleton_horse": "骷髅马",
    "minecraft:slime": "史莱姆",
    "minecraft:small_fireball": "小型火球",
    "minecraft:sniffer": "嗅探兽",
    "minecraft:snow_golem": "雪傀儡",
    "minecraft:snowball": "雪球",
    "minecraft:spider": "蜘蛛",
    "minecraft:splash_potion": "喷溅药水",
    "minecraft:squid": "鱿鱼",
    "minecraft:stray": "流浪者",
    "minecraft:strider": "炽足兽",
    "minecraft:tadpole": "蝌蚪",
    "minecraft:thrown_trident": "投掷的三叉戟",
    "minecraft:tnt": "TNT",
    "minecraft:tnt_minecart": "TNT矿车",
    "minecraft:trader_llama": "行商羊驼",
    "minecraft:tripod_camera": "三脚架摄像机",
    "minecraft:tropicalfish": "热带鱼",
    "minecraft:turtle": "海龟",
    "minecraft:vex": "恼鬼",
    "minecraft:villager": "村民",
    "minecraft:villager_v2": "村民V2",
    "minecraft:vindicator": "卫道士",
    "minecraft:wandering_trader": "流浪商人",
    "minecraft:warden": "监守者",
    "minecraft:wind_charge_projectile": "旋风人风弹",
    "minecraft:witch": "女巫",
    "minecraft:wither": "凋灵",
    "minecraft:wither_skeleton": "凋灵骷髅",
    "minecraft:wither_skull": "凋灵骷髅头颅",
    "minecraft:wither_skull_dangerous": "蓝色凋灵之首",
    "minecraft:wolf": "狼",
    "minecraft:xp_bottle": "经验瓶",
    "minecraft:xp_orb": "经验球",
    "minecraft:zoglin": "僵尸疣猪兽",
    "minecraft:zombie": "僵尸",
    "minecraft:zombie_horse": "僵尸马",
    "minecraft:zombie_pigman": "僵尸猪人",
    "minecraft:zombie_villager": "僵尸村民",
    "minecraft:zombie_villager_v2": "僵尸村民V2",
    "物品":"##################################################仅未重复",
    "minecraft:acacia_boat": "金合欢木船",
    "minecraft:acacia_chest_boat": "金合欢木箱子船",
    "minecraft:acacia_sign": "金合欢木告示牌",
    "minecraft:agent_spawn_egg": "代理生成蛋",
    "minecraft:allay_spawn_egg": "悦灵生成蛋",
    "minecraft:amethyst_shard": "紫水晶碎片",
    "minecraft:angler_pottery_sherd": "钓鱼者陶片",
    "minecraft:apple": "苹果",
    "minecraft:archer_pottery_sherd": "弓箭手陶片",
    "minecraft:armadillo_scute": "犰狳甲",
    "minecraft:armadillo_spawn_egg": "犰狳生成蛋",
    "minecraft:arms_up_pottery_sherd": "举手陶片",
    "minecraft:axolotl_bucket": "装有墨西哥钝口螈的桶",
    "minecraft:axolotl_spawn_egg": "墨西哥钝口螈生成蛋",
    "minecraft:baked_potato": "烤马铃薯",
    "minecraft:bamboo_chest_raft": "竹箱子筏",
    "minecraft:bamboo_raft": "竹筏",
    "minecraft:bamboo_sign": "竹告示牌",
    "minecraft:banner": "旗帜",
    "minecraft:banner_pattern": "旗帜图案",
    "minecraft:bat_spawn_egg": "蝙蝠生成蛋",
    "minecraft:bee_spawn_egg": "蜜蜂生成蛋",
    "minecraft:beef": "牛肉",
    "minecraft:beetroot_seeds": "甜菜种子",
    "minecraft:beetroot_soup": "甜菜汤",
    "minecraft:birch_boat": "白桦木船",
    "minecraft:birch_chest_boat": "白桦木箱子船",
    "minecraft:birch_sign": "白桦木告示牌",
    "minecraft:black_dye": "黑色染料",
    "minecraft:blade_pottery_sherd": "刀片陶片",
    "minecraft:blaze_powder": "烈焰粉",
    "minecraft:blaze_rod": "烈焰棒",
    "minecraft:blaze_spawn_egg": "烈焰人生成蛋",
    "minecraft:bleach": "漂白粉",
    "minecraft:blue_dye": "蓝色染料",
    "minecraft:bogged_spawn_egg": "沼骸生成蛋",
    "minecraft:bolt_armor_trim_smithing_template": "镶铆盔甲纹饰锻造模板",
    "minecraft:bone": "骨头",
    "minecraft:bone_meal": "骨粉",
    "minecraft:book": "书",
    "minecraft:bordure_indented_banner_pattern": "凹形边缘旗帜图案",
    "minecraft:bow": "弓",
    "minecraft:bowl": "碗",
    "minecraft:bread": "面包",
    "minecraft:breeze_rod": "旋风棒",
    "minecraft:breeze_spawn_egg": "旋风人生成蛋",
    "minecraft:brewer_pottery_sherd": "酿酒者陶片",
    "minecraft:brick": "砖块",
    "minecraft:brown_dye": "棕色染料",
    "minecraft:brush": "刷子",
    "minecraft:bucket": "桶",
    "minecraft:burn_pottery_sherd": "燃烧陶片",
    "minecraft:camel_spawn_egg": "骆驼生成蛋",
    "minecraft:carpet": "地毯",
    "minecraft:carrot": "胡萝卜",
    "minecraft:carrot_on_a_stick": "胡萝卜钓竿",
    "minecraft:cat_spawn_egg": "猫生成蛋",
    "minecraft:cave_spider_spawn_egg": "洞穴蜘蛛生成蛋",
    "minecraft:chainmail_boots": "锁链靴",
    "minecraft:chainmail_chestplate": "锁链胸甲",
    "minecraft:chainmail_helmet": "锁链头盔",
    "minecraft:chainmail_leggings": "锁链护腿",
    "minecraft:charcoal": "木炭",
    "minecraft:chemistry_table": "化学台",
    "minecraft:cherry_boat": "樱花木船",
    "minecraft:cherry_chest_boat": "樱花木箱子船",
    "minecraft:cherry_sign": "樱花木告示牌",
    "minecraft:chicken_spawn_egg": "鸡生成蛋",
    "minecraft:chorus_fruit": "紫颂果",
    "minecraft:clay_ball": "粘土球",
    "minecraft:clock": "时钟",
    "minecraft:coal": "煤炭",
    "minecraft:coast_armor_trim_smithing_template": "海岸纹饰盔甲锻造模板",
    "minecraft:cocoa_beans": "可可豆",
    "minecraft:cod_bucket": "装有鳕鱼的桶",
    "minecraft:cod_spawn_egg": "鳕鱼生成蛋",
    "minecraft:colored_torch_bp": "彩色火把",
    "minecraft:colored_torch_rg": "彩色火把",
    "minecraft:comparator": "比较器",
    "minecraft:compass": "指南针",
    "minecraft:compound": "化合物",
    "minecraft:concrete": "混凝土",
    "minecraft:concrete_powder": "混凝土粉末",
    "minecraft:cooked_beef": "牛排",
    "minecraft:cooked_chicken": "熟鸡肉",
    "minecraft:cooked_cod": "熟鳕鱼",
    "minecraft:cooked_mutton": "熟羊肉",
    "minecraft:cooked_porkchop": "熟猪排",
    "minecraft:cooked_rabbit": "熟兔肉",
    "minecraft:cooked_salmon": "熟鲑鱼",
    "minecraft:cookie": "曲奇",
    "minecraft:copper_ingot": "铜锭",
    "minecraft:coral": "珊瑚",
    "minecraft:coral_block": "珊瑚块",
    "minecraft:coral_fan": "珊瑚扇",
    "minecraft:cow_spawn_egg": "牛生成蛋",
    "minecraft:creeper_banner_pattern": "爬行者旗帜图案",
    "minecraft:creeper_spawn_egg": "爬行者生成蛋",
    "minecraft:crimson_sign": "绯红告示牌",
    "minecraft:crossbow": "弩",
    "minecraft:cyan_dye": "青色染料",
    "minecraft:danger_pottery_sherd": "危险陶片",
    "minecraft:dark_oak_boat": "深色橡木船",
    "minecraft:dark_oak_chest_boat": "深色橡木箱子船",
    "minecraft:dark_oak_sign": "深色橡木告示牌",
    "minecraft:debug_stick": "调试棒",
    "minecraft:diamond": "钻石",
    "minecraft:diamond_axe": "钻石斧",
    "minecraft:diamond_boots": "钻石靴",
    "minecraft:diamond_chestplate": "钻石胸甲",
    "minecraft:diamond_helmet": "钻石头盔",
    "minecraft:diamond_hoe": "钻石锄",
    "minecraft:diamond_horse_armor": "钻石马铠",
    "minecraft:diamond_leggings": "钻石护腿",
    "minecraft:diamond_pickaxe": "钻石镐",
    "minecraft:diamond_shovel": "钻石铲",
    "minecraft:diamond_sword": "钻石剑",
    "minecraft:disc_fragment_5": "唱片碎片",
    "minecraft:dolphin_spawn_egg": "海豚生成蛋",
    "minecraft:donkey_spawn_egg": "驴生成蛋",
    "minecraft:double_stone_block_slab": "双石台阶",
    "minecraft:double_stone_block_slab2": "双石台阶",
    "minecraft:double_stone_block_slab3": "双石台阶",
    "minecraft:double_stone_block_slab4": "双石台阶",
    "minecraft:dragon_breath": "龙息",
    "minecraft:dried_kelp": "干海带",
    "minecraft:drowned_spawn_egg": "淹死鬼生成蛋",
    "minecraft:dune_armor_trim_smithing_template": "沙丘纹饰盔甲锻造模板",
    "minecraft:dye": "染料",
    "minecraft:echo_shard": "回声碎片",
    "minecraft:elder_guardian_spawn_egg": "远古守卫者生成蛋",
    "minecraft:elytra": "鞘翅",
    "minecraft:emerald": "绿宝石",
    "minecraft:empty_map": "空地图",
    "minecraft:enchanted_book": "附魔书",
    "minecraft:enchanted_golden_apple": "附魔金苹果",
    "minecraft:end_crystal": "末影水晶",
    "minecraft:ender_dragon_spawn_egg": "末影龙生成蛋",
    "minecraft:ender_eye": "末影之眼",
    "minecraft:enderman_spawn_egg": "末影人生成蛋",
    "minecraft:endermite_spawn_egg": "末影螨生成蛋",
    "minecraft:evoker_spawn_egg": "唤魔者生成蛋",
    "minecraft:experience_bottle": "经验瓶",
    "minecraft:explorer_pottery_sherd": "探险家陶片",
    "minecraft:eye_armor_trim_smithing_template": "眼眸盔甲纹饰锻造模板",
    "minecraft:feather": "羽毛",
    "minecraft:fence": "栅栏",
    "minecraft:fermented_spider_eye": "发酵蜘蛛眼",
    "minecraft:field_masoned_banner_pattern": "田野石匠旗帜图案",
    "minecraft:filled_map": "已填充地图",
    "minecraft:fire_charge": "火焰弹",
    "minecraft:firework_rocket": "烟花火箭",
    "minecraft:firework_star": "烟花星形",
    "minecraft:fishing_rod": "钓鱼竿",
    "minecraft:flint": "燧石",
    "minecraft:flint_and_steel": "打火石",
    "minecraft:flow_armor_trim_smithing_template": "涡流盔甲纹饰锻造模板",
    "minecraft:flow_banner_pattern": "流动旗帜图案",
    "minecraft:flow_pottery_sherd": "流动陶片",
    "minecraft:flower_banner_pattern": "花朵旗帜图案",
    "minecraft:fox_spawn_egg": "狐狸生成蛋",
    "minecraft:friend_pottery_sherd": "朋友陶片",
    "minecraft:frog_spawn_egg": "青蛙生成蛋",
    "minecraft:ghast_spawn_egg": "恶魂生成蛋",
    "minecraft:ghast_tear": "恶魂之泪",
    "minecraft:glass_bottle": "玻璃瓶",
    "minecraft:glistering_melon_slice": "闪烁的西瓜片",
    "minecraft:globe_banner_pattern": "地球旗帜图案",
    "minecraft:glow_ink_sac": "发光墨囊",
    "minecraft:glow_squid_spawn_egg": "发光鱿鱼生成蛋",
    "minecraft:glow_stick": "荧光棒",
    "minecraft:glowstone_dust": "荧石粉",
    "minecraft:goat_horn": "山羊角",
    "minecraft:goat_spawn_egg": "山羊生成蛋",
    "minecraft:gold_ingot": "金锭",
    "minecraft:gold_nugget": "金粒",
    "minecraft:golden_apple": "金苹果",
    "minecraft:golden_axe": "金斧",
    "minecraft:golden_boots": "金靴",
    "minecraft:golden_carrot": "金胡萝卜",
    "minecraft:golden_chestplate": "金胸甲",
    "minecraft:golden_helmet": "金头盔",
    "minecraft:golden_hoe": "金锄",
    "minecraft:golden_horse_armor": "金马铠",
    "minecraft:golden_leggings": "金护腿",
    "minecraft:golden_pickaxe": "金镐",
    "minecraft:golden_shovel": "金铲",
    "minecraft:golden_sword": "金剑",
    "minecraft:gray_dye": "灰色染料",
    "minecraft:green_dye": "绿色染料",
    "minecraft:guardian_spawn_egg": "守卫者生成蛋",
    "minecraft:gunpowder": "火药",
    "minecraft:guster_banner_pattern": "风暴旗帜图案",
    "minecraft:guster_pottery_sherd": "风暴陶片",
    "minecraft:hard_cyan_stained_glass": "硬青色染色玻璃",
    "minecraft:hard_cyan_stained_glass_pane": "硬青色染色玻璃板",
    "minecraft:hard_stained_glass_pane": "硬染色玻璃板",
    "minecraft:heart_of_the_sea": "海之心脏",
    "minecraft:heart_pottery_sherd": "心形陶片",
    "minecraft:heartbreak_pottery_sherd": "心碎陶片",
    "minecraft:hoglin_spawn_egg": "霍格林生成蛋",
    "minecraft:honey_bottle": "蜂蜜瓶",
    "minecraft:honeycomb": "蜂窝",
    "minecraft:horse_spawn_egg": "马生成蛋",
    "minecraft:host_armor_trim_smithing_template": "雇主盔甲纹饰锻造模板",
    "minecraft:howl_pottery_sherd": "嚎叫陶片",
    "minecraft:husk_spawn_egg": "尸壳生成蛋",
    "minecraft:ink_sac": "墨囊",
    "minecraft:iron_axe": "铁斧",
    "minecraft:iron_boots": "铁靴",
    "minecraft:iron_chestplate": "铁胸甲",
    "minecraft:iron_golem_spawn_egg": "铁傀儡生成蛋",
    "minecraft:iron_helmet": "铁头盔",
    "minecraft:iron_hoe": "铁锄",
    "minecraft:iron_horse_armor": "铁马铠",
    "minecraft:iron_ingot": "铁锭",
    "minecraft:iron_leggings": "铁护腿",
    "minecraft:iron_nugget": "铁粒",
    "minecraft:iron_pickaxe": "铁镐",
    "minecraft:iron_shovel": "铁铲",
    "minecraft:iron_sword": "铁剑",
    "minecraft:jungle_boat": "丛林木船",
    "minecraft:jungle_chest_boat": "丛林木箱子船",
    "minecraft:jungle_sign": "丛林木告示牌",
    "minecraft:lapis_lazuli": "青金石",
    "minecraft:lava_bucket": "熔岩桶",
    "minecraft:lead": "牵绳",
    "minecraft:leather": "皮革",
    "minecraft:leather_boots": "皮靴",
    "minecraft:leather_chestplate": "皮胸甲",
    "minecraft:leather_helmet": "皮头盔",
    "minecraft:leather_horse_armor": "皮革马铠",
    "minecraft:leather_leggings": "皮护腿",
    "minecraft:leaves": "树叶",
    "minecraft:leaves2": "树叶",
    "minecraft:light_block": "光源方块",
    "minecraft:light_block_16": "光源方块",
    "minecraft:light_blue_dye": "浅蓝色染料",
    "minecraft:light_gray_dye": "浅灰色染料",
    "minecraft:lime_dye": "黄绿色染料",
    "minecraft:llama_spawn_egg": "羊驼生成蛋",
    "minecraft:lodestone_compass": "磁石指南针",
    "minecraft:log": "原木",
    "minecraft:log2": "原木",
    "minecraft:mace": "权杖",
    "minecraft:magenta_dye": "品红色染料",
    "minecraft:magma_cream": "岩浆膏",
    "minecraft:magma_cube_spawn_egg": "岩浆怪生成蛋",
    "minecraft:mangrove_boat": "红树林船",
    "minecraft:mangrove_chest_boat": "红树林箱子船",
    "minecraft:mangrove_sign": "红树林告示牌",
    "minecraft:medicine": "药水",
    "minecraft:melon_seeds": "西瓜种子",
    "minecraft:melon_slice": "西瓜片",
    "minecraft:milk_bucket": "牛奶桶",
    "minecraft:miner_pottery_sherd": "矿工陶片",
    "minecraft:mojang_banner_pattern": "Mojang旗帜图案",
    "minecraft:monster_egg": "怪物蛋",
    "minecraft:mooshroom_spawn_egg": "哞菇生成蛋",
    "minecraft:mourner_pottery_sherd": "哀悼者陶片",
    "minecraft:mule_spawn_egg": "骡生成蛋",
    "minecraft:mushroom_stew": "蘑菇汤",
    "minecraft:music_disc_11": "11号唱片",
    "minecraft:music_disc_13": "13号唱片",
    "minecraft:music_disc_5": "5号唱片",
    "minecraft:music_disc_blocks": "街区唱片",
    "minecraft:music_disc_cat": "猫唱片",
    "minecraft:music_disc_chirp": "唧唧唱片",
    "minecraft:music_disc_creator": "创造者唱片",
    "minecraft:music_disc_creator_music_box": "创造者音乐盒唱片",
    "minecraft:music_disc_far": "远方唱片",
    "minecraft:music_disc_mall": "商场唱片",
    "minecraft:music_disc_mellohi": "你好唱片",
    "minecraft:music_disc_otherside": "另一面唱片",
    "minecraft:music_disc_pigstep": "猪步唱片",
    "minecraft:music_disc_precipice": "悬崖唱片",
    "minecraft:music_disc_relic": "遗迹唱片",
    "minecraft:music_disc_stal": "石笋唱片",
    "minecraft:music_disc_strad": "斯特拉德唱片",
    "minecraft:music_disc_wait": "等待唱片",
    "minecraft:music_disc_ward": "守护唱片",
    "minecraft:mutton": "羊肉",
    "minecraft:name_tag": "命名牌",
    "minecraft:nautilus_shell": "鹦鹉螺壳",
    "minecraft:nether_star": "下界之星",
    "minecraft:netherbrick": "下界砖",
    "minecraft:netherite_axe": "下界合金斧",
    "minecraft:netherite_boots": "下界合金靴",
    "minecraft:netherite_chestplate": "下界合金胸甲",
    "minecraft:netherite_helmet": "下界合金头盔",
    "minecraft:netherite_hoe": "下界合金锄",
    "minecraft:netherite_ingot": "下界合金锭",
    "minecraft:netherite_leggings": "下界合金护腿",
    "minecraft:netherite_pickaxe": "下界合金镐",
    "minecraft:netherite_scrap": "下界合金碎片",
    "minecraft:netherite_shovel": "下界合金铲",
    "minecraft:netherite_sword": "下界合金剑",
    "minecraft:netherite_upgrade_smithing_template": "下界合金升级锻造模板",
    "minecraft:npc_spawn_egg": "NPC生成蛋",
    "minecraft:oak_boat": "橡木船",
    "minecraft:oak_chest_boat": "橡木箱子船",
    "minecraft:oak_sign": "橡木告示牌",
    "minecraft:ocelot_spawn_egg": "豹猫生成蛋",
    "minecraft:ominous_bottle": "不祥之瓶",
    "minecraft:ominous_trial_key": "不祥试炼钥匙",
    "minecraft:orange_dye": "橙色染料",
    "minecraft:panda_spawn_egg": "熊猫生成蛋",
    "minecraft:paper": "纸",
    "minecraft:parrot_spawn_egg": "鹦鹉生成蛋",
    "minecraft:phantom_membrane": "幻翼膜",
    "minecraft:phantom_spawn_egg": "幻翼生成蛋",
    "minecraft:pig_spawn_egg": "猪生成蛋",
    "minecraft:piglin_banner_pattern": "猪灵旗帜图案",
    "minecraft:piglin_brute_spawn_egg": "猪灵蛮兵生成蛋",
    "minecraft:piglin_spawn_egg": "猪灵生成蛋",
    "minecraft:pillager_spawn_egg": "掠夺者生成蛋",
    "minecraft:pink_dye": "粉红色染料",
    "minecraft:pitcher_pod": "投手荚",
    "minecraft:planks": "木板",
    "minecraft:plenty_pottery_sherd": "丰富陶片",
    "minecraft:poisonous_potato": "毒马铃薯",
    "minecraft:polar_bear_spawn_egg": "北极熊生成蛋",
    "minecraft:popped_chorus_fruit": "爆裂紫颂果",
    "minecraft:porkchop": "生猪排",
    "minecraft:potato": "马铃薯",
    "minecraft:potion": "药水",
    "minecraft:powder_snow_bucket": "粉雪桶",
    "minecraft:prismarine_crystals": "海晶砂晶",
    "minecraft:prismarine_shard": "海晶碎片",
    "minecraft:prize_pottery_sherd": "奖品陶片",
    "minecraft:pufferfish_bucket": "装有河豚的桶",
    "minecraft:pufferfish_spawn_egg": "河豚生成蛋",
    "minecraft:pumpkin_pie": "南瓜派",
    "minecraft:pumpkin_seeds": "南瓜种子",
    "minecraft:purple_dye": "紫色染料",
    "minecraft:quartz": "下界石英",
    "minecraft:rabbit_foot": "兔子脚",
    "minecraft:rabbit_hide": "兔子皮",
    "minecraft:rabbit_spawn_egg": "兔子生成蛋",
    "minecraft:rabbit_stew": "兔肉汤",
    "minecraft:raiser_armor_trim_smithing_template": "牧民盔甲纹饰锻造模板",
    "minecraft:rapid_fertilizer": "快速肥料",
    "minecraft:ravager_spawn_egg": "劫掠兽生成蛋",
    "minecraft:raw_copper": "生铜",
    "minecraft:raw_gold": "生金",
    "minecraft:raw_iron": "生铁",
    "minecraft:recovery_compass": "恢复指南针",
    "minecraft:red_dye": "红色染料",
    "minecraft:redstone": "红石",
    "minecraft:repeater": "红石中继器",
    "minecraft:rib_armor_trim_smithing_template": "肋骨盔甲纹饰锻造模板",
    "minecraft:rotten_flesh": "腐肉",
    "minecraft:saddle": "鞍",
    "minecraft:salmon_bucket": "装有鲑鱼的桶",
    "minecraft:salmon_spawn_egg": "鲑鱼生成蛋",
    "minecraft:sapling": "树苗",
    "minecraft:scrape_pottery_sherd": "刮擦陶片",
    "minecraft:sentry_armor_trim_smithing_template": "哨兵盔甲纹饰锻造模板",
    "minecraft:shaper_armor_trim_smithing_template": "塑造盔甲纹饰锻造模板",
    "minecraft:sheaf_pottery_sherd": "捆束陶片",
    "minecraft:shears": "剪刀",
    "minecraft:sheep_spawn_egg": "羊生成蛋",
    "minecraft:shelter_pottery_sherd": "庇护所陶片",
    "minecraft:shulker_box": "潜影盒",
    "minecraft:shulker_shell": "潜影壳",
    "minecraft:shulker_spawn_egg": "潜影贝生成蛋",
    "minecraft:silence_armor_trim_smithing_template": "幽静盔甲纹饰锻造模板",
    "minecraft:silverfish_spawn_egg": "蠹虫生成蛋",
    "minecraft:skeleton_horse_spawn_egg": "骷髅马生成蛋",
    "minecraft:skeleton_spawn_egg": "骷髅生成蛋",
    "minecraft:skull_banner_pattern": "头骨旗帜图案",
    "minecraft:skull_pottery_sherd": "头骨陶片",
    "minecraft:slime_ball": "粘液球",
    "minecraft:slime_spawn_egg": "史莱姆生成蛋",
    "minecraft:sniffer_spawn_egg": "嗅探者生成蛋",
    "minecraft:snort_pottery_sherd": "喷气陶片",
    "minecraft:snout_armor_trim_smithing_template": "猪鼻盔甲纹饰锻造模板",
    "minecraft:snow_golem_spawn_egg": "雪傀儡生成蛋",
    "minecraft:sparkler": "火花器",
    "minecraft:spawn_egg": "生成蛋",
    "minecraft:spider_eye": "蜘蛛眼",
    "minecraft:spider_spawn_egg": "蜘蛛生成蛋",
    "minecraft:spire_armor_trim_smithing_template": "尖塔盔甲纹饰锻造模板",
    "minecraft:spruce_boat": "云杉木船",
    "minecraft:spruce_chest_boat": "云杉木箱子船",
    "minecraft:spruce_sign": "云杉木告示牌",
    "minecraft:spyglass": "望远镜",
    "minecraft:squid_spawn_egg": "鱿鱼生成蛋",
    "minecraft:stained_glass": "染色玻璃",
    "minecraft:stained_glass_pane": "染色玻璃板",
    "minecraft:stained_hardened_clay": "染色硬化粘土",
    "minecraft:stick": "木棍",
    "minecraft:stone_axe": "石斧",
    "minecraft:stone_hoe": "石锄",
    "minecraft:stone_pickaxe": "石镐",
    "minecraft:stone_shovel": "石铲",
    "minecraft:stone_sword": "石剑",
    "minecraft:stonebrick": "石砖",
    "minecraft:stray_spawn_egg": "流浪者生成蛋",
    "minecraft:strider_spawn_egg": "炽足兽生成蛋",
    "minecraft:string": "线",
    "minecraft:sugar": "糖",
    "minecraft:sugar_cane": "甘蔗",
    "minecraft:suspicious_stew": "可疑的炖菜",
    "minecraft:sweet_berries": "甜浆果",
    "minecraft:tadpole_bucket": "装有蝌蚪的桶",
    "minecraft:tadpole_spawn_egg": "蝌蚪生成蛋",
    "minecraft:tallgrass": "高草丛",
    "minecraft:tide_armor_trim_smithing_template": "潮汐盔甲纹饰锻造模板",
    "minecraft:torchflower_seeds": "火把花种子",
    "minecraft:totem_of_undying": "不死图腾",
    "minecraft:trader_llama_spawn_egg": "行商羊驼生成蛋",
    "minecraft:trial_key": "试炼钥匙",
    "minecraft:trident": "三叉戟",
    "minecraft:tropical_fish": "热带鱼",
    "minecraft:tropical_fish_bucket": "装有热带鱼的桶",
    "minecraft:tropical_fish_spawn_egg": "热带鱼生成蛋",
    "minecraft:turtle_helmet": "海龟壳",
    "minecraft:turtle_scute": "海龟鳞片",
    "minecraft:turtle_spawn_egg": "海龟生成蛋",
    "minecraft:vex_armor_trim_smithing_template": "恼鬼盔甲纹饰锻造模板",
    "minecraft:vex_spawn_egg": "恼鬼生成蛋",
    "minecraft:villager_spawn_egg": "村民生成蛋",
    "minecraft:vindicator_spawn_egg": "卫道士生成蛋",
    "minecraft:wandering_trader_spawn_egg": "流浪商人生成蛋",
    "minecraft:ward_armor_trim_smithing_template": "坚守盔甲纹饰锻造模板",
    "minecraft:warden_spawn_egg": "守望者生成蛋",
    "minecraft:warped_fungus_on_a_stick": "诡异菌棒",
    "minecraft:warped_sign": "诡异告示牌",
    "minecraft:water_bucket": "水桶",
    "minecraft:wayfinder_armor_trim_smithing_template": "向导盔甲纹饰锻造模板",
    "minecraft:wheat_seeds": "小麦种子",
    "minecraft:white_dye": "白色染料",
    "minecraft:wild_armor_trim_smithing_template": "荒野盔甲纹饰锻造模板",
    "minecraft:wind_charge": "风之电荷",
    "minecraft:witch_spawn_egg": "女巫生成蛋",
    "minecraft:wither_skeleton_spawn_egg": "凋灵骷髅生成蛋",
    "minecraft:wither_spawn_egg": "凋灵生成蛋",
    "minecraft:wolf_armor": "狼盔甲",
    "minecraft:wolf_spawn_egg": "狼生成蛋",
    "minecraft:wood": "木头",
    "minecraft:wooden_axe": "木斧",
    "minecraft:wooden_hoe": "木锄",
    "minecraft:wooden_pickaxe": "木镐",
    "minecraft:wooden_shovel": "木铲",
    "minecraft:wooden_slab": "木台阶",
    "minecraft:wooden_sword": "木剑",
    "minecraft:wool": "羊毛",
    "minecraft:writable_book": "可写书",
    "minecraft:written_book": "已写书",
    "minecraft:yellow_dye": "黄色染料",
    "minecraft:zoglin_spawn_egg": "僵尸疣猪生成蛋",
    "minecraft:zombie_horse_spawn_egg": "僵尸马生成蛋",
    "minecraft:zombie_pigman_spawn_egg": "僵尸猪灵生成蛋",
    "minecraft:zombie_spawn_egg": "僵尸生成蛋",
    "minecraft:zombie_villager_spawn_egg": "僵尸村民生成蛋",
    "附魔效果":"###################################################################",
    "aqua_affinity":"水下速掘",
    "bane_of_arthropods":"节肢杀手",
    "blast_protection":"爆炸保护",
    "channeling":"引雷",
    "binding":"绑定诅咒",
    "vanishing":"消失诅咒",
    "depth_strider":"深海探索者",
    "efficiency":"效率",
    "feather_falling":"摔落缓冲",
    "fire_aspect":"火焰附加",
    "fire_protection":"火焰保护",
    "flame":"火矢",
    "fortune":"时运",
    "frost_walker":"冰霜行者",
    "impaling":"穿刺",
    "infinity":"无限",
    "knockback":"击退",
    "looting":"抢夺",
    "loyalty":"忠诚",
    "luck_of_the_sea":"海之眷顾",
    "lure":"饵钓",
    "mending":"经验修补",
    "multishot":"多重射击",
    "piercing":"穿透",
    "power":"力量",
    "projectile_protection":"弹射物保护",
    "protection":"保护",
    "punch":"冲击",
    "quick_charge":"快速装填",
    "respiration":"水下呼吸",
    "riptide":"激流",
    "sharpness":"锋利",
    "silk_touch":"精准采集",
    "smite":"亡灵杀手",
    "soul_speed":"灵魂疾行",
    "swift_sneak":"迅捷潜行",
    "thorns":"荆棘",
    "unbreaking":"耐久",
    "density":"致密",
    "breach":"破甲",
    "wind_burst":"风爆",
    "花名":"################################################",
    "minecraft:dandelion":"蒲公英",
    "minecraft:poppy":"虞美人",
    "minecraft:blue_orchid":"兰花",
    "minecraft:allium":"绒球葱",
    "minecraft:azure_bluet":"蓝花美耳草",
    "minecraft:red_tulip":"红色郁金香",
    "minecraft:orange_tulip":"橙色郁金香",
    "minecraft:white_tulip":"白色郁金香",
    "minecraft:pink_tulip":"粉红色郁金香",
    "minecraft:oxeye_daisy":"滨菊",
    "minecraft:cornflower":"矢车菊",
    "minecraft:lily_of_the_valley":"",
    "minecraft:sunflower":"铃兰",
    "minecraft:lilac":"向日葵",
    "minecraft:rose_bush":"丁香",
    "minecraft:peony":"玫瑰丛",
    "minecraft:wither_rose":"牡丹",
    "minecraft:torchflower":"凋灵玫瑰",
    "minecraft:pitcher_plant":"火把花",
};